// lib/seed-movies.ts — Film Glance 5K Movie Seed List
// Organized into 5 batches for incremental seeding.
// Duplicates across categories are expected and deduplicated at runtime.
//
// Batch 1: IMDb Top 250 + Major Film Festival Winners & Nominees (718)
// Batch 2: Franchises & Animation (400+)
// Batch 3: Horror, Action/Adventure, Sci-Fi, Thriller (600+)
// Batch 4: Comedy, Romance, Crime, War, Sports, Musicals, Documentary (600+)
// Batch 5: Director Filmographies, International Cinema, Cult Classics, 2024-2026 (600+)

// ─── BATCH 1: IMDb Top 250 + Film Festivals & Awards ───────────────────────

export const BATCH_1: string[] = [
  // IMDb Top 250 (core)
  "The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Godfather Part II",
  "12 Angry Men", "Schindler's List", "The Lord of the Rings: The Return of the King",
  "Pulp Fiction", "The Lord of the Rings: The Fellowship of the Ring", "The Good, the Bad and the Ugly",
  "Forrest Gump", "Fight Club", "The Lord of the Rings: The Two Towers", "Inception",
  "Star Wars: Episode V - The Empire Strikes Back", "The Matrix", "Goodfellas",
  "One Flew Over the Cuckoo's Nest", "Se7en", "Seven Samurai",
  "It's a Wonderful Life", "The Silence of the Lambs", "City of God",
  "Saving Private Ryan", "Life Is Beautiful", "The Green Mile",
  "Interstellar", "Terminator 2: Judgment Day", "Back to the Future",
  "Spirited Away", "The Pianist", "Psycho",
  "The Usual Suspects", "Parasite", "Léon: The Professional",
  "The Lion King", "Gladiator", "American History X",
  "The Departed", "Whiplash", "The Prestige",
  "Casablanca", "Harakiri", "Grave of the Fireflies",
  "The Intouchables", "Modern Times", "Rear Window",
  "Cinema Paradiso", "Alien", "City Lights",
  "Apocalypse Now", "Memento", "Django Unchained",
  "Indiana Jones and the Raiders of the Lost Ark", "WALL·E", "The Lives of Others",
  "Sunset Boulevard", "Paths of Glory", "The Shining",
  "The Great Dictator", "Witness for the Prosecution", "Aliens",
  "American Beauty", "The Dark Knight Rises", "Spider-Man: Into the Spider-Verse",
  "Avengers: Infinity War", "Braveheart", "Joker",
  "Good Will Hunting", "Toy Story", "Amadeus",
  "Coco", "Avengers: Endgame", "Princess Mononoke",
  "Once Upon a Time in the West", "Your Name", "Hamilton",
  "The Hunt", "3 Idiots", "Requiem for a Dream",
  "Eternal Sunshine of the Spotless Mind", "Full Metal Jacket",
  "Singin' in the Rain", "2001: A Space Odyssey", "Ikiru",
  "Taxi Driver", "Toy Story 3", "Lawrence of Arabia",
  "Amélie", "A Clockwork Orange", "North by Northwest",
  "Das Boot", "Vertigo", "Double Indemnity",
  "Bicycle Thieves", "Come and See", "Capernaum",
  "To Kill a Mockingbird", "The Kid", "Dangal",
  "The Apartment", "Inglourious Basterds", "Snatch",
  "Scarface", "M", "Like Stars on Earth",
  "For a Few Dollars More", "Metropolis", "The Sting",
  "A Separation", "1917", "Rashomon",
  "Up", "All About Eve", "Heat",
  "Batman Begins", "Some Like It Hot", "Downfall",
  "The Wolf of Wall Street", "Unforgiven", "A Beautiful Mind",
  "The Treasure of the Sierra Madre", "Dial M for Murder", "Raging Bull",
  "No Country for Old Men", "Casino", "Pan's Labyrinth",
  "There Will Be Blood", "The Truman Show", "Shutter Island",
  "My Neighbor Totoro", "The Grand Budapest Hotel", "Howl's Moving Castle",
  "Pather Panchali", "The Secret in Their Eyes", "The Bridge on the River Kwai",
  "Lock, Stock and Two Smoking Barrels", "Prisoners", "The General",
  "Catch Me If You Can", "Blade Runner", "The Gold Rush",
  "Chinatown", "Inside Out", "Fargo",
  "Monty Python and the Holy Grail", "The Thing", "The Seventh Seal",
  "On the Waterfront", "Stalker", "The Elephant Man",
  "Gone with the Wind", "The Third Man", "Wild Strawberries",
  "Finding Nemo", "Ran", "Oldboy",
  "Tokyo Story", "Klaus", "Room",
  "Spotlight", "The Sixth Sense", "Kill Bill: Vol. 1",
  "The Great Escape", "Gone Girl", "Network",
  "Blade Runner 2049", "The Wages of Fear", "12 Years a Slave",
  "Gran Torino", "Arrival", "The Banshees of Inisherin",
  "Mad Max: Fury Road", "The Handmaiden", "In the Name of the Father",
  "The Deer Hunter", "Cool Hand Luke", "Hachi: A Dog's Tale",
  "Everything Everywhere All at Once", "Mr. Smith Goes to Washington",
  "Judgment at Nuremberg", "Hacksaw Ridge",
  "Andrei Rublev", "La Haine", "Memories of Murder",
  "Barry Lyndon", "The Father", "Before Sunrise",
  "Wild Tales", "The Passion of Joan of Arc", "The Circus",
  "Monsters, Inc.", "Stand by Me", "The Big Lebowski",
  "Ratatouille", "Spring, Summer, Fall, Winter... and Spring",
  "Incendies", "Mary and Max", "The Best Years of Our Lives",
  "Ben-Hur", "Amores Perros", "In the Mood for Love",
  "Yojimbo", "Million Dollar Baby", "Grave of the Fireflies",
  "The Exorcist", "Persona", "The Night of the Hunter",

  // Oscar Best Picture Winners (comprehensive)
  "Wings", "The Broadway Melody", "All Quiet on the Western Front",
  "Cimarron", "Grand Hotel", "Cavalcade", "It Happened One Night",
  "Mutiny on the Bounty", "The Great Ziegfeld", "The Life of Emile Zola",
  "You Can't Take It with You", "Gone with the Wind", "Rebecca",
  "How Green Was My Valley", "Mrs. Miniver", "Going My Way",
  "The Lost Weekend", "The Best Years of Our Lives", "Gentleman's Agreement",
  "Hamlet", "All the King's Men", "All About Eve",
  "An American in Paris", "The Greatest Show on Earth", "From Here to Eternity",
  "On the Waterfront", "Marty", "Around the World in 80 Days",
  "The Bridge on the River Kwai", "Gigi", "Ben-Hur",
  "The Apartment", "West Side Story", "Lawrence of Arabia",
  "Tom Jones", "My Fair Lady", "The Sound of Music",
  "A Man for All Seasons", "In the Heat of the Night", "Oliver!",
  "Midnight Cowboy", "Patton", "The French Connection",
  "The Godfather", "The Sting", "The Godfather Part II",
  "One Flew Over the Cuckoo's Nest", "Rocky", "Annie Hall",
  "The Deer Hunter", "Kramer vs. Kramer", "Ordinary People",
  "Chariots of Fire", "Gandhi", "Terms of Endearment",
  "Amadeus", "Out of Africa", "Platoon",
  "The Last Emperor", "Rain Man", "Driving Miss Daisy",
  "Dances with Wolves", "The Silence of the Lambs", "Unforgiven",
  "Schindler's List", "Forrest Gump", "Braveheart",
  "The English Patient", "Titanic", "Shakespeare in Love",
  "American Beauty", "Gladiator", "A Beautiful Mind",
  "Chicago", "The Lord of the Rings: The Return of the King", "Million Dollar Baby",
  "Crash", "The Departed", "No Country for Old Men",
  "Slumdog Millionaire", "The Hurt Locker", "The King's Speech",
  "The Artist", "Argo", "12 Years a Slave",
  "Birdman", "Spotlight", "Moonlight",
  "The Shape of Water", "Green Book", "Parasite",
  "Nomadland", "CODA", "Everything Everywhere All at Once",
  "Oppenheimer", "Anora",

  // Oscar Best Picture Nominees (2000-2026 — non-winners)
  "Chocolat", "Crouching Tiger, Hidden Dragon", "Erin Brockovich",
  "Gladiator", "Traffic", "Gosford Park",
  "In the Bedroom", "Moulin Rouge!", "The Pianist",
  "Gangs of New York", "The Hours", "The Two Towers",
  "City of God", "Finding Nemo", "Lost in Translation",
  "Master and Commander: The Far Side of the World", "Mystic River", "Seabiscuit",
  "The Aviator", "Finding Neverland", "Ray",
  "Sideways", "Capote", "Good Night, and Good Luck",
  "Munich", "Babel", "The Queen",
  "Letters from Iwo Jima", "Little Miss Sunshine", "Atonement",
  "Juno", "Michael Clayton", "There Will Be Blood",
  "The Curious Case of Benjamin Button", "Frost/Nixon", "Milk",
  "The Reader", "Avatar", "The Blind Side",
  "District 9", "An Education", "Inglourious Basterds",
  "Precious", "A Serious Man", "Up",
  "Up in the Air", "127 Hours", "Black Swan",
  "The Fighter", "The Kids Are All Right", "The Social Network",
  "Toy Story 3", "True Grit", "Winter's Bone",
  "The Descendants", "Extremely Loud & Incredibly Close", "The Help",
  "Hugo", "Midnight in Paris", "Moneyball",
  "The Tree of Life", "War Horse", "Amour",
  "Beasts of the Southern Wild", "Django Unchained", "Les Misérables",
  "Life of Pi", "Lincoln", "Silver Linings Playbook",
  "Zero Dark Thirty", "American Hustle", "Captain Phillips",
  "Dallas Buyers Club", "Gravity", "Her",
  "Nebraska", "Philomena", "The Wolf of Wall Street",
  "Boyhood", "The Grand Budapest Hotel", "The Imitation Game",
  "Selma", "The Theory of Everything", "The Big Short",
  "Bridge of Spies", "Brooklyn", "Mad Max: Fury Road",
  "The Martian", "The Revenant", "Room",
  "Arrival", "Fences", "Hacksaw Ridge",
  "Hell or High Water", "Hidden Figures", "La La Land",
  "Lion", "Manchester by the Sea", "Call Me by Your Name",
  "Darkest Hour", "Dunkirk", "Get Out",
  "Lady Bird", "Phantom Thread", "The Post",
  "Three Billboards Outside Ebbing, Missouri", "BlackKklansman", "Black Panther",
  "Bohemian Rhapsody", "The Favourite", "Roma",
  "A Star Is Born", "Vice", "Ford v Ferrari",
  "The Irishman", "JoJo Rabbit", "Joker",
  "Little Women", "Marriage Story", "1917",
  "Once Upon a Time in Hollywood", "Judas and the Black Messiah",
  "Mank", "Minari", "The Father",
  "Promising Young Woman", "Sound of Metal", "The Trial of the Chicago 7",
  "Belfast", "Don't Look Up", "Drive My Car",
  "Dune", "King Richard", "Licorice Pizza",
  "Nightmare Alley", "The Power of the Dog", "West Side Story",
  "All Quiet on the Western Front", "The Banshees of Inisherin",
  "Elvis", "The Fabelmans", "Tár",
  "Top Gun: Maverick", "Triangle of Sadness", "Women Talking",
  "American Fiction", "Anatomy of a Fall", "Barbie",
  "The Holdovers", "Killers of the Flower Moon", "Maestro",
  "Past Lives", "Poor Things", "The Zone of Interest",
  "The Brutalist", "A Complete Unknown", "Conclave",
  "Dune: Part Two", "Emilia Pérez", "I'm Still Here",
  "Nickel Boys", "The Substance", "Wicked",

  // Cannes Palme d'Or Winners (comprehensive)
  "Marty", "The Cranes Are Flying", "Black Orpheus",
  "La Dolce Vita", "Viridiana", "The Leopard",
  "The Umbrellas of Cherbourg", "A Man and a Woman", "Blow-Up",
  "M*A*S*H", "The Go-Between", "The Working Class Goes to Heaven",
  "The Mattei Affair", "Scarecrow", "The Hireling",
  "The Conversation", "Chronicle of the Years of Fire",
  "Taxi Driver", "The Tree of Wooden Clogs", "Apocalypse Now",
  "All That Jazz", "Kagemusha", "Man of Iron",
  "Missing", "Yol", "The Ballad of Narayama",
  "Paris, Texas", "When Father Was Away on Business", "The Mission",
  "Under the Sun of Satan", "Pelle the Conqueror", "sex, lies, and videotape",
  "Wild at Heart", "Barton Fink", "The Best Intentions",
  "Farewell My Concubine", "The Piano", "Pulp Fiction",
  "Underground", "Secrets & Lies", "The Eel",
  "A Taste of Cherry", "Eternity and a Day", "Rosetta",
  "Dancer in the Dark", "The Son's Room", "The Pianist",
  "Elephant", "Fahrenheit 9/11", "L'Enfant",
  "The Wind That Shakes the Barley", "4 Months, 3 Weeks and 2 Days",
  "The Class", "The White Ribbon", "Uncle Boonmee Who Can Recall His Past Lives",
  "The Tree of Life", "Amour", "Blue Is the Warmest Colour",
  "Winter Sleep", "Dheepan", "I, Daniel Blake",
  "The Square", "Shoplifters", "Parasite",
  "Titane", "Triangle of Sadness", "Anatomy of a Fall",
  "Anora",

  // Cannes Grand Prix
  "The Lobster", "It's Only the End of the World", "A Man of Integrity",
  "BlacKkKlansman", "Atlantics", "The Father",
  "A Hero", "Close", "All We Imagine as Light",

  // Venice Golden Lion Winners
  "Rashomon", "Monsoon Wedding", "The Magdalene Sisters",
  "The Return", "Brokeback Mountain", "Still Life",
  "Lust, Caution", "The Wrestler", "Lebanon",
  "Somewhere", "Faust", "Pieta",
  "Sacro GRA", "A Pigeon Sat on a Branch Reflecting on Existence",
  "From Afar", "The Woman Who Left", "The Shape of Water",
  "Roma", "Joker", "Nomadland",
  "Happening", "All the Beauty and the Bloodshed", "Poor Things",
  "The Room Next Door",

  // Berlin Golden Bear Winners
  "Spirited Away", "Bloody Sunday", "In This World",
  "Head-On", "U-Carmen eKhayelitsha", "Grbavica",
  "Tuya's Marriage", "Elite Squad", "The Milk of Sorrow",
  "Honey", "A Separation", "Caesar Must Die",
  "Child's Pose", "Black Coal, Thin Ice", "Taxi",
  "Fire at Sea", "On Body and Soul", "Touch Me Not",
  "Synonyms", "There Is No Evil", "Bad Luck Banging or Loony Porn",
  "Alcarràs", "On the Adamant", "Dahomey",

  // Toronto People's Choice Award
  "American Beauty", "Crouching Tiger, Hidden Dragon", "Monsoon Wedding",
  "Whale Rider", "Hotel Rwanda", "Tsotsi",
  "Bella", "Slumdog Millionaire", "Precious",
  "The King's Speech", "Where Do We Go Now?", "Silver Linings Playbook",
  "12 Years a Slave", "The Imitation Game", "Room",
  "La La Land", "Three Billboards Outside Ebbing, Missouri", "Green Book",
  "Jojo Rabbit", "Nomadland", "Belfast",
  "The Fabelmans", "American Fiction", "The Brutalist",

  // Sundance Grand Jury Prize (Drama)
  "Beasts of the Southern Wild", "Fruitvale Station", "Whiplash",
  "Me and Earl and the Dying Girl", "The Birth of a Nation",
  "I Don't Feel at Home in This World Anymore",
  "The Miseducation of Cameron Post", "Clemency", "Minari",
  "CODA", "Nanny", "A Thousand and One", "A Real Pain",

  // BAFTA Best Film Winners (recent)
  "The Hurt Locker", "The King's Speech", "The Artist",
  "Argo", "12 Years a Slave", "Boyhood",
  "The Revenant", "La La Land", "Three Billboards Outside Ebbing, Missouri",
  "Roma", "1917", "Nomadland",
  "The Power of the Dog", "All Quiet on the Western Front",
  "Oppenheimer", "Conclave",

  // Golden Globe Best Picture Drama Winners (recent)
  "The Social Network", "The Descendants", "Argo",
  "12 Years a Slave", "Boyhood", "The Revenant",
  "Moonlight", "Three Billboards Outside Ebbing, Missouri",
  "Bohemian Rhapsody", "1917", "Nomadland",
  "The Power of the Dog", "The Fabelmans", "Oppenheimer",
  "The Brutalist",

  // Golden Globe Best Picture Comedy/Musical Winners (recent)
  "The Kids Are All Right", "The Artist", "Les Misérables",
  "American Hustle", "The Grand Budapest Hotel", "The Martian",
  "La La Land", "Lady Bird", "Green Book",
  "Once Upon a Time in Hollywood", "Borat Subsequent Moviefilm",
  "West Side Story", "The Banshees of Inisherin", "Poor Things",
  "Emilia Pérez",

  // César Best Film (French Oscars)
  "The Intouchables", "Amour", "Les Misérables",
  "The Taste of Things", "Emilia Pérez",

  // Goya Best Film (Spanish Oscars)
  "The Sea Inside", "Pan's Labyrinth", "The Secret in Their Eyes",
  "Pain and Glory", "The Good Boss", "Beast",

  // Spirit Awards Best Feature (recent)
  "Moonlight", "Get Out", "If Beale Street Could Talk",
  "The Farewell", "Nomadland", "The Lost Daughter",
  "Everything Everywhere All at Once", "Past Lives", "Anora",

  // SAG Outstanding Cast (recent)
  "The Help", "Argo", "American Hustle",
  "Birdman", "Spotlight", "Hidden Figures",
  "Three Billboards Outside Ebbing, Missouri", "Black Panther",
  "Parasite", "The Trial of the Chicago 7", "CODA",
  "Everything Everywhere All at Once", "Oppenheimer", "Emilia Pérez",
];

// ─── BATCH 2: Franchises & Animation ────────────────────────────────────────

export const BATCH_2: string[] = [
  // MCU (all 34 films)
  "Iron Man", "The Incredible Hulk", "Iron Man 2", "Thor",
  "Captain America: The First Avenger", "The Avengers", "Iron Man 3",
  "Thor: The Dark World", "Captain America: The Winter Soldier",
  "Guardians of the Galaxy", "Avengers: Age of Ultron", "Ant-Man",
  "Captain America: Civil War", "Doctor Strange", "Guardians of the Galaxy Vol. 2",
  "Spider-Man: Homecoming", "Thor: Ragnarok", "Black Panther",
  "Avengers: Infinity War", "Ant-Man and the Wasp", "Captain Marvel",
  "Avengers: Endgame", "Spider-Man: Far From Home", "Black Widow",
  "Shang-Chi and the Legend of the Ten Rings", "Eternals",
  "Spider-Man: No Way Home", "Doctor Strange in the Multiverse of Madness",
  "Thor: Love and Thunder", "Black Panther: Wakanda Forever",
  "Ant-Man and the Wasp: Quantumania", "Guardians of the Galaxy Vol. 3",
  "The Marvels", "Deadpool & Wolverine",

  // DC Films
  "Man of Steel", "Batman v Superman: Dawn of Justice", "Suicide Squad",
  "Wonder Woman", "Justice League", "Aquaman",
  "Shazam!", "Birds of Prey", "Wonder Woman 1984",
  "Zack Snyder's Justice League", "The Suicide Squad", "Black Adam",
  "Shazam! Fury of the Gods", "The Flash", "Blue Beetle", "Aquaman and the Lost Kingdom",
  // Standalone DC
  "Batman", "Batman Returns", "Batman Forever", "Batman & Robin",
  "Batman Begins", "The Dark Knight", "The Dark Knight Rises", "The Batman",
  "Superman", "Superman II", "Superman Returns",
  "Joker", "Joker: Folie à Deux",
  "The Penguin",

  // Star Wars (all saga + spinoffs)
  "Star Wars: Episode IV - A New Hope", "Star Wars: Episode V - The Empire Strikes Back",
  "Star Wars: Episode VI - Return of the Jedi",
  "Star Wars: Episode I - The Phantom Menace", "Star Wars: Episode II - Attack of the Clones",
  "Star Wars: Episode III - Revenge of the Sith",
  "Star Wars: The Force Awakens", "Rogue One: A Star Wars Story",
  "Star Wars: The Last Jedi", "Solo: A Star Wars Story",
  "Star Wars: The Rise of Skywalker",

  // James Bond (all 25)
  "Dr. No", "From Russia with Love", "Goldfinger", "Thunderball",
  "You Only Live Twice", "On Her Majesty's Secret Service",
  "Diamonds Are Forever", "Live and Let Die", "The Man with the Golden Gun",
  "The Spy Who Loved Me", "Moonraker", "For Your Eyes Only",
  "Octopussy", "A View to a Kill", "The Living Daylights",
  "Licence to Kill", "GoldenEye", "Tomorrow Never Dies",
  "The World Is Not Enough", "Die Another Day", "Casino Royale",
  "Quantum of Solace", "Skyfall", "Spectre", "No Time to Die",

  // Harry Potter + Fantastic Beasts
  "Harry Potter and the Sorcerer's Stone", "Harry Potter and the Chamber of Secrets",
  "Harry Potter and the Prisoner of Azkaban", "Harry Potter and the Goblet of Fire",
  "Harry Potter and the Order of the Phoenix", "Harry Potter and the Half-Blood Prince",
  "Harry Potter and the Deathly Hallows – Part 1", "Harry Potter and the Deathly Hallows – Part 2",
  "Fantastic Beasts and Where to Find Them", "Fantastic Beasts: The Crimes of Grindelwald",
  "Fantastic Beasts: The Secrets of Dumbledore",

  // Pixar (all ~28 films)
  "Toy Story", "A Bug's Life", "Toy Story 2", "Monsters, Inc.",
  "Finding Nemo", "The Incredibles", "Cars", "Ratatouille",
  "WALL·E", "Up", "Toy Story 3", "Cars 2",
  "Brave", "Monsters University", "Inside Out", "The Good Dinosaur",
  "Finding Dory", "Cars 3", "Coco", "Incredibles 2",
  "Toy Story 4", "Onward", "Soul", "Luca",
  "Turning Red", "Lightyear", "Elemental", "Inside Out 2",
  "Elio",

  // Disney Animation (major releases)
  "Snow White and the Seven Dwarfs", "Pinocchio", "Fantasia", "Dumbo",
  "Bambi", "Cinderella", "Alice in Wonderland", "Peter Pan",
  "Lady and the Tramp", "Sleeping Beauty", "101 Dalmatians",
  "The Jungle Book", "The Aristocats", "Robin Hood",
  "The Fox and the Hound", "The Little Mermaid", "Beauty and the Beast",
  "Aladdin", "The Lion King", "Pocahontas",
  "The Hunchback of Notre Dame", "Hercules", "Mulan",
  "Tarzan", "The Emperor's New Groove", "Atlantis: The Lost Empire",
  "Lilo & Stitch", "Treasure Planet", "Brother Bear",
  "Bolt", "The Princess and the Frog", "Tangled",
  "Winnie the Pooh", "Wreck-It Ralph", "Frozen",
  "Big Hero 6", "Zootopia", "Moana",
  "Ralph Breaks the Internet", "Frozen II", "Raya and the Last Dragon",
  "Encanto", "Strange World", "Wish", "Moana 2",

  // Studio Ghibli (all major films)
  "Nausicaä of the Valley of the Wind", "Castle in the Sky", "My Neighbor Totoro",
  "Grave of the Fireflies", "Kiki's Delivery Service", "Only Yesterday",
  "Porco Rosso", "Pom Poko", "Whisper of the Heart",
  "Princess Mononoke", "My Neighbors the Yamadas",
  "Spirited Away", "The Cat Returns", "Howl's Moving Castle",
  "Tales from Earthsea", "Ponyo", "Arrietty",
  "From Up on Poppy Hill", "The Wind Rises", "The Tale of the Princess Kaguya",
  "When Marnie Was There", "The Boy and the Heron",

  // DreamWorks Animation
  "Antz", "The Prince of Egypt", "Shrek", "Shrek 2",
  "Shrek the Third", "Shrek Forever After",
  "Madagascar", "Madagascar: Escape 2 Africa", "Madagascar 3: Europe's Most Wanted",
  "Kung Fu Panda", "Kung Fu Panda 2", "Kung Fu Panda 3", "Kung Fu Panda 4",
  "How to Train Your Dragon", "How to Train Your Dragon 2", "How to Train Your Dragon: The Hidden World",
  "Megamind", "Puss in Boots", "Puss in Boots: The Last Wish",
  "The Croods", "The Croods: A New Age",
  "Trolls", "Trolls World Tour", "Trolls Band Together",
  "The Boss Baby", "The Bad Guys", "Orion and the Dark",
  "The Wild Robot",

  // Other Animation
  "Ice Age", "Ice Age: The Meltdown", "Ice Age: Dawn of the Dinosaurs",
  "Ice Age: Continental Drift", "Ice Age: Collision Course",
  "Despicable Me", "Despicable Me 2", "Despicable Me 3", "Despicable Me 4",
  "Minions", "Minions: The Rise of Gru",
  "The Lego Movie", "The Lego Movie 2: The Second Part", "The Lego Batman Movie",
  "Spider-Man: Into the Spider-Verse", "Spider-Man: Across the Spider-Verse",
  "Coraline", "ParaNorman", "Kubo and the Two Strings",
  "Missing Link", "Wolfwalkers", "The Mitchells vs. the Machines",
  "Akira", "Ghost in the Shell", "Paprika",
  "Weathering with You", "Suzume", "The First Slam Dunk",
  "Demon Slayer: Mugen Train", "One Piece Film: Red",
  "Dragon Ball Super: Broly", "Dragon Ball Super: Super Hero",
  "Howl's Moving Castle", "Persepolis", "Waltz with Bashir",
  "The Secret of Kells", "Song of the Sea", "Flee",
  "My Life as a Zucchini", "I Lost My Body",
  "The Nightmare Before Christmas", "Corpse Bride", "Fantastic Mr. Fox",
  "Isle of Dogs", "Wallace & Gromit: The Curse of the Were-Rabbit",
  "Chicken Run", "Chicken Run: Dawn of the Nugget",
  "Shaun the Sheep Movie", "Early Man",
  "The Iron Giant", "Megamind", "Sing", "Sing 2",
  "The Secret Life of Pets", "The Secret Life of Pets 2",
  "Ferdinand", "Migration", "Spies in Disguise",
  "Abominable", "Spirit Untamed", "The Sea Beast",
  "Nimona", "Wish Dragon", "Over the Moon",
  "Guillermo del Toro's Pinocchio", "Marcel the Shell with Shoes On",
  "Robot Dreams", "Flow", "Memoir of a Snail",
  "Look Back",

  // X-Men Franchise
  "X-Men", "X2", "X-Men: The Last Stand",
  "X-Men: First Class", "The Wolverine", "X-Men: Days of Future Past",
  "X-Men: Apocalypse", "Logan", "Dark Phoenix", "The New Mutants",
  "Deadpool", "Deadpool 2",

  // Spider-Man (non-MCU)
  "Spider-Man", "Spider-Man 2", "Spider-Man 3",
  "The Amazing Spider-Man", "The Amazing Spider-Man 2",
  "Venom", "Venom: Let There Be Carnage", "Venom: The Last Dance",
  "Morbius", "Madame Web",

  // Lord of the Rings / Hobbit
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Return of the King",
  "The Hobbit: An Unexpected Journey", "The Hobbit: The Desolation of Smaug",
  "The Hobbit: The Battle of the Five Armies",

  // Rocky / Creed
  "Rocky", "Rocky II", "Rocky III", "Rocky IV", "Rocky Balboa",
  "Creed", "Creed II", "Creed III",

  // The Conjuring Universe (extended)
  "The Conjuring", "The Conjuring 2", "The Conjuring: The Devil Made Me Do It",
  "Annabelle", "Annabelle: Creation", "Annabelle Comes Home",
  "The Nun", "The Nun II",

  // Monsterverse extended
  "Cloverfield", "10 Cloverfield Lane", "The Cloverfield Paradox",

  // Additional franchises
  "Men in Black", "Men in Black II", "Men in Black 3", "Men in Black: International",
  "Ghostbusters", "Ghostbusters II", "Ghostbusters: Afterlife", "Ghostbusters: Frozen Empire",
  "The Mummy", "The Mummy Returns", "The Mummy: Tomb of the Dragon Emperor",
  "Night at the Museum", "Night at the Museum: Battle of the Smithsonian",
  "Night at the Museum: Secret of the Tomb",
  "Shrek", "Shrek 2", "Shrek the Third", "Shrek Forever After",
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
  "The Chronicles of Narnia: Prince Caspian",
  "The Chronicles of Narnia: The Voyage of the Dawn Treader",
  "Twilight", "The Twilight Saga: New Moon", "The Twilight Saga: Eclipse",
  "The Twilight Saga: Breaking Dawn – Part 1", "The Twilight Saga: Breaking Dawn – Part 2",
  "The Expendables", "The Expendables 2", "The Expendables 3",
];

// ─── BATCH 3: Horror, Action/Adventure, Sci-Fi, Thriller ───────────────────

export const BATCH_3: string[] = [
  // Horror — Major Franchises
  "The Conjuring", "The Conjuring 2", "The Conjuring: The Devil Made Me Do It",
  "Annabelle", "Annabelle: Creation", "Annabelle Comes Home",
  "The Nun", "The Nun II", "The Curse of La Llorona",
  "Scream", "Scream 2", "Scream 3", "Scream 4", "Scream (2022)", "Scream VI",
  "Halloween", "Halloween II", "Halloween III: Season of the Witch",
  "Halloween 4: The Return of Michael Myers", "Halloween 5: The Revenge of Michael Myers",
  "Halloween H20: 20 Years Later", "Halloween (2018)", "Halloween Kills", "Halloween Ends",
  "A Nightmare on Elm Street", "A Nightmare on Elm Street 3: Dream Warriors",
  "Wes Craven's New Nightmare",
  "Friday the 13th", "Friday the 13th Part 2", "Friday the 13th: The Final Chapter",
  "Saw", "Saw II", "Saw III", "Saw IV", "Saw V", "Saw VI",
  "Jigsaw", "Spiral", "Saw X",
  "Insidious", "Insidious: Chapter 2", "Insidious: Chapter 3",
  "Insidious: The Last Key", "Insidious: The Red Door",
  "The Purge", "The Purge: Anarchy", "The Purge: Election Year", "The First Purge",
  "The Forever Purge",
  "Paranormal Activity", "Paranormal Activity 2", "Paranormal Activity 3",
  "Paranormal Activity: The Marked Ones",
  "Final Destination", "Final Destination 2", "Final Destination 3",
  "The Final Destination", "Final Destination 5", "Final Destination Bloodlines",
  "It", "It Chapter Two",
  "Child's Play", "Bride of Chucky", "Curse of Chucky",
  "The Texas Chain Saw Massacre", "The Texas Chainsaw Massacre (2003)",
  "Hellraiser", "Hellraiser (2022)",
  "The Ring", "The Ring Two", "The Grudge", "The Grudge (2020)",

  // Horror — A24 & Elevated Horror
  "Hereditary", "Midsommar", "The Witch", "The Lighthouse",
  "X", "Pearl", "MaXXXine", "Talk to Me",
  "Bodies Bodies Bodies", "Men", "Lamb",
  "It Comes at Night", "A Ghost Story", "Under the Skin",
  "The Killing of a Sacred Deer", "Saint Maud",

  // Horror — Classics & Modern Standalone
  "The Exorcist", "The Shining", "Psycho", "Rosemary's Baby",
  "The Omen", "Carrie", "Poltergeist", "The Thing",
  "An American Werewolf in London", "The Fly", "Evil Dead II",
  "Candyman", "The Blair Witch Project",
  "28 Days Later", "The Babadook", "It Follows",
  "The Cabin in the Woods", "Tucker and Dale vs Evil",
  "Ready or Not", "Happy Death Day", "Happy Death Day 2U",
  "Don't Breathe", "Don't Breathe 2", "Hush",
  "A Quiet Place", "A Quiet Place Part II", "A Quiet Place: Day One",
  "Us", "Nope", "The Invisible Man",
  "Barbarian", "Smile", "Smile 2",
  "M3GAN", "Terrifier", "Terrifier 2", "Terrifier 3",
  "The Black Phone", "Malignant", "Old",
  "Pearl", "Longlegs", "Late Night with the Devil",
  "Speak No Evil", "Alien: Romulus", "The Substance",
  "Nosferatu", "Heretic", "The Menu",
  "Fresh", "Bones and All", "The Night House",

  // Horror — International & Extended
  "Ringu", "Ju-On: The Grudge", "Audition", "Dark Water",
  "Let the Right One In", "The Orphanage", "REC", "REC 2",
  "Train to Busan", "Peninsula", "The Wailing", "I Saw the Devil",
  "Suspiria", "Suspiria (2018)", "Raw", "Titane",
  "Goodnight Mommy", "The Platform", "The Platform 2", "Incantation",
  "Tumbbad", "Impetigore", "Satan's Slaves",
  "The Autopsy of Jane Doe", "The Ritual", "The Descent", "The Descent Part 2",
  "28 Days Later", "28 Weeks Later",
  "Shaun of the Dead", "Zombieland", "Zombieland: Double Tap",
  "World War Z", "Army of the Dead",
  "Sinister", "Sinister 2", "Oculus", "Gerald's Game",
  "Doctor Sleep", "Pet Sematary", "Pet Sematary (2019)",
  "Christine", "Misery", "The Mist", "Cujo", "1408",
  "Creepshow", "From Dusk Till Dawn", "Grindhouse",
  "Drag Me to Hell", "Evil Dead Rise",
  "Trick 'r Treat", "Krampus",
  "The Strangers", "The Strangers: Chapter 1",
  "You're Next", "The Guest", "Green Room", "Blue Ruin",
  "Bone Tomahawk", "Mandy", "Color Out of Space",
  "Possessor", "Infinity Pool", "Neon Demon", "Climax",
  "Martyrs", "Inside", "High Tension",
  "Megan Is Missing", "Creep", "Creep 2",
  "Host", "V/H/S", "V/H/S/2",
  "Gonjiam: Haunted Asylum", "The Medium", "Noroi: The Curse",
  "One Cut of the Dead", "Pulse",
  "Candyman", "Candyman (2021)", "The Blair Witch Project",
  "As Above, So Below", "Grave Encounters",
  "The Conjuring", "Annabelle", "The Nun",
  "Lights Out", "Don't Breathe", "Crawl",
  "The Invisible Man", "Underwater",
  "The Witch", "The Lighthouse", "Hereditary", "Midsommar",
  "It Follows", "The Babadook", "Get Out", "Us",
  "The Cabin in the Woods", "Tucker and Dale vs Evil",
  "The House That Jack Built", "Antichrist",

  // Action — Fast & Furious (all)
  "The Fast and the Furious", "2 Fast 2 Furious", "The Fast and the Furious: Tokyo Drift",
  "Fast & Furious", "Fast Five", "Fast & Furious 6",
  "Furious 7", "The Fate of the Furious", "F9", "Fast X",

  // Action — Mission: Impossible (all)
  "Mission: Impossible", "Mission: Impossible 2", "Mission: Impossible III",
  "Mission: Impossible – Ghost Protocol", "Mission: Impossible – Rogue Nation",
  "Mission: Impossible – Fallout", "Mission: Impossible – Dead Reckoning Part One",

  // Action — John Wick (all)
  "John Wick", "John Wick: Chapter 2", "John Wick: Chapter 3 – Parabellum",
  "John Wick: Chapter 4", "Ballerina",

  // Action — Die Hard
  "Die Hard", "Die Hard 2", "Die Hard with a Vengeance", "Live Free or Die Hard",
  "A Good Day to Die Hard",

  // Action — Terminator (all)
  "The Terminator", "Terminator 2: Judgment Day", "Terminator 3: Rise of the Machines",
  "Terminator Salvation", "Terminator Genisys", "Terminator: Dark Fate",

  // Action — Alien franchise
  "Alien", "Aliens", "Alien 3", "Alien Resurrection",
  "Prometheus", "Alien: Covenant", "Alien: Romulus",
  "Alien vs. Predator", "Aliens vs. Predator: Requiem",

  // Action — Predator franchise
  "Predator", "Predator 2", "Predators", "The Predator", "Prey",

  // Action — Jurassic Park/World
  "Jurassic Park", "The Lost World: Jurassic Park", "Jurassic Park III",
  "Jurassic World", "Jurassic World: Fallen Kingdom", "Jurassic World Dominion",

  // Action — Godzilla/Kong
  "Godzilla (2014)", "Kong: Skull Island", "Godzilla: King of the Monsters",
  "Godzilla vs. Kong", "Godzilla x Kong: The New Empire",
  "Godzilla Minus One", "Shin Godzilla",

  // Action — Mad Max
  "Mad Max", "Mad Max 2: The Road Warrior", "Mad Max Beyond Thunderdome",
  "Mad Max: Fury Road", "Furiosa: A Mad Max Saga",

  // Action — Planet of the Apes
  "Planet of the Apes", "Rise of the Planet of the Apes",
  "Dawn of the Planet of the Apes", "War for the Planet of the Apes",
  "Kingdom of the Planet of the Apes",

  // Action — Other Franchises
  "Bad Boys", "Bad Boys II", "Bad Boys for Life", "Bad Boys: Ride or Die",
  "The Equalizer", "The Equalizer 2", "The Equalizer 3",
  "Taken", "Taken 2", "Taken 3",
  "Kingsman: The Secret Service", "Kingsman: The Golden Circle", "The King's Man",
  "The Expendables", "The Expendables 2", "The Expendables 3", "Expend4bles",
  "Rambo", "Rambo: First Blood Part II", "Rambo III", "Rambo (2008)", "Rambo: Last Blood",
  "First Blood",
  "The Bourne Identity", "The Bourne Supremacy", "The Bourne Ultimatum",
  "The Bourne Legacy", "Jason Bourne",
  "Transformers", "Transformers: Revenge of the Fallen", "Transformers: Dark of the Moon",
  "Transformers: Age of Extinction", "Transformers: The Last Knight",
  "Bumblebee", "Transformers: Rise of the Beasts",
  "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Pirates of the Caribbean: Dead Man's Chest",
  "Pirates of the Caribbean: At World's End",
  "Pirates of the Caribbean: On Stranger Tides",
  "Pirates of the Caribbean: Dead Men Tell No Tales",
  "Indiana Jones and the Raiders of the Lost Ark", "Indiana Jones and the Temple of Doom",
  "Indiana Jones and the Last Crusade", "Indiana Jones and the Kingdom of the Crystal Skull",
  "Indiana Jones and the Dial of Destiny",
  "The Hunger Games", "The Hunger Games: Catching Fire",
  "The Hunger Games: Mockingjay – Part 1", "The Hunger Games: Mockingjay – Part 2",
  "The Hunger Games: The Ballad of Songbirds & Snakes",
  "Divergent", "Insurgent", "Allegiant",
  "The Maze Runner", "Maze Runner: The Scorch Trials", "Maze Runner: The Death Cure",
  "300", "300: Rise of an Empire",

  // Action — Standalone
  "Gladiator", "Gladiator II", "Troy", "Braveheart",
  "Kill Bill: Vol. 1", "Kill Bill: Vol. 2",
  "The Raid", "The Raid 2", "Ip Man", "Ip Man 2", "Ip Man 3", "Ip Man 4",
  "Crouching Tiger, Hidden Dragon", "Hero", "House of Flying Daggers",
  "Extraction", "Extraction 2", "The Gray Man",
  "Nobody", "Bullet Train", "Ambulance",
  "Monkey Man", "The Fall Guy", "Rebel Ridge",
  "Civil War", "Twisters",

  // Sci-Fi — Classics & Modern
  "2001: A Space Odyssey", "Blade Runner", "Blade Runner 2049",
  "The Matrix", "The Matrix Reloaded", "The Matrix Revolutions", "The Matrix Resurrections",
  "Dune", "Dune: Part Two",
  "Arrival", "Interstellar", "Gravity", "The Martian",
  "Ad Astra", "First Man", "Hidden Figures",
  "Ex Machina", "Annihilation", "Upgrade",
  "Edge of Tomorrow", "Oblivion", "Elysium",
  "District 9", "Chappie", "I, Robot",
  "Minority Report", "War of the Worlds", "A.I. Artificial Intelligence",
  "Close Encounters of the Third Kind", "E.T. the Extra-Terrestrial",
  "Contact", "Solaris", "Stalker",
  "Moon", "Sunshine", "Prospect",
  "Everything Everywhere All at Once", "Tenet", "Nope",
  "Coherence", "Primer", "Donnie Darko",
  "The Lobster", "Her", "Eternal Sunshine of the Spotless Mind",
  "Children of Men", "Snowpiercer", "The Road",
  "Looper", "Source Code", "Inception",
  "Ready Player One", "Free Guy", "The Creator",
  "Atlas", "I Am Mother", "Vivarium",
  "Under the Skin", "High Life", "Aniara",
  "Mickey 17",

  // Thriller — Hitchcock Essentials
  "Psycho", "Rear Window", "Vertigo", "North by Northwest",
  "The Birds", "Rope", "Strangers on a Train",
  "Dial M for Murder", "Notorious", "Rebecca",
  "Shadow of a Doubt", "The 39 Steps", "Lifeboat",

  // Thriller — Modern
  "Gone Girl", "Zodiac", "Prisoners", "Sicario", "Sicario: Day of the Soldado",
  "Nightcrawler", "Se7en", "Silence of the Lambs",
  "The Talented Mr. Ripley", "Shutter Island", "Black Swan",
  "American Psycho", "Uncut Gems", "Good Time",
  "Nocturnal Animals", "Wind River", "Hell or High Water",
  "Knives Out", "Glass Onion", "Wake Up Dead Man",
  "The Girl with the Dragon Tattoo", "The Girl on the Train",
  "Gone Baby Gone", "Mystic River", "A Simple Favor",
  "Widows", "The Invisible Man", "Run",
  "Salt", "Red Sparrow", "Atomic Blonde",
  "Tár", "The Banshees of Inisherin", "The Killer",
  "Saltburn", "May December", "Dream Scenario",
  "Conclave", "Juror #2",
];

// ─── BATCH 4: Comedy, Romance, Crime, War, Sports, Musicals, Documentary ────

export const BATCH_4: string[] = [
  // Comedy — Franchises
  "The Hangover", "The Hangover Part II", "The Hangover Part III",
  "Meet the Parents", "Meet the Fockers", "Little Fockers",
  "Ghostbusters", "Ghostbusters II", "Ghostbusters: Afterlife", "Ghostbusters: Frozen Empire",
  "Austin Powers: International Man of Mystery", "Austin Powers: The Spy Who Shagged Me",
  "Austin Powers in Goldmember",
  "Ace Ventura: Pet Detective", "Ace Ventura: When Nature Calls",
  "Scary Movie", "Scary Movie 2", "Scary Movie 3",
  "Wayne's World", "Wayne's World 2",
  "Bill & Ted's Excellent Adventure", "Bill & Ted Face the Music",
  "Jackass: The Movie", "Jackass Forever",
  "Ted", "Ted 2",
  "Neighbors", "Neighbors 2: Sorority Rising",
  "Jump Street", "22 Jump Street",
  "Anchorman: The Legend of Ron Burgundy", "Anchorman 2: The Legend Continues",
  "Zoolander", "Zoolander 2",
  "Rush Hour", "Rush Hour 2", "Rush Hour 3",
  "Beverly Hills Cop", "Beverly Hills Cop II", "Beverly Hills Cop: Axel F",

  // Comedy — Classics & Standalone
  "Superbad", "Step Brothers", "Talladega Nights", "The Other Guys",
  "Elf", "Blades of Glory", "Semi-Pro",
  "Bridesmaids", "The Heat", "Spy", "Ghostbusters (2016)",
  "The 40-Year-Old Virgin", "Knocked Up", "This Is 40",
  "Forgetting Sarah Marshall", "Get Him to the Greek",
  "Pineapple Express", "This Is the End", "The Interview",
  "Tropic Thunder", "Dodgeball", "School of Rock",
  "Napoleon Dynamite", "Borat", "Borat Subsequent Moviefilm",
  "The Grand Budapest Hotel", "The Royal Tenenbaums",
  "Rushmore", "The Life Aquatic with Steve Zissou",
  "Hot Fuzz", "Shaun of the Dead", "The World's End",
  "In Bruges", "The Nice Guys", "Kiss Kiss Bang Bang",
  "The Big Lebowski", "Fargo", "Burn After Reading",
  "Groundhog Day", "Ferris Bueller's Day Off", "Planes, Trains and Automobiles",
  "National Lampoon's Vacation", "National Lampoon's Christmas Vacation",
  "Mrs. Doubtfire", "The Birdcage", "Liar Liar",
  "Bruce Almighty", "The Mask", "Dumb and Dumber",
  "Tommy Boy", "Billy Madison", "Happy Gilmore",
  "The Waterboy", "Big Daddy", "Mr. Deeds",
  "50 First Dates", "Click", "Grown Ups",
  "Uncut Gems", "The Wedding Singer",
  "Office Space", "Idiocracy",
  "Mean Girls", "Mean Girls (2024)", "Clueless", "Legally Blonde",
  "Legally Blonde 2", "Pitch Perfect", "Pitch Perfect 2",
  "Booksmart", "Lady Bird", "The Edge of Seventeen",
  "Easy A", "Game Night", "Horrible Bosses",
  "We're the Millers", "Central Intelligence",
  "The Internship", "Free Guy", "Glass Onion",
  "Barbie", "Don't Look Up", "The Menu",
  "Everything Everywhere All at Once", "The Banshees of Inisherin",
  "American Fiction", "Dream Scenario", "Bottoms",
  "No Hard Feelings", "Theater Camp", "Joy Ride",
  "Hit Man", "A Real Pain", "Saturday Night",
  "Anora",

  // Romance & Rom-Com
  "When Harry Met Sally", "Pretty Woman", "Sleepless in Seattle",
  "You've Got Mail", "Notting Hill", "Love Actually",
  "The Notebook", "A Walk to Remember", "Dear John",
  "The Longest Ride", "Safe Haven", "The Best of Me",
  "Message in a Bottle", "Nights in Rodanthe",
  "10 Things I Hate About You", "She's All That", "How to Lose a Guy in 10 Days",
  "27 Dresses", "The Proposal", "Just Go with It",
  "Hitch", "Maid in Manhattan", "Two Weeks Notice",
  "My Big Fat Greek Wedding", "My Big Fat Greek Wedding 2", "My Big Fat Greek Wedding 3",
  "Crazy Rich Asians", "To All the Boys I've Loved Before",
  "Set It Up", "Always Be My Maybe", "The Big Sick",
  "About Time", "The Time Traveler's Wife", "One Day",
  "Before Sunrise", "Before Sunset", "Before Midnight",
  "Eternal Sunshine of the Spotless Mind", "500 Days of Summer",
  "Silver Linings Playbook", "La La Land",
  "Call Me by Your Name", "Portrait of a Lady on Fire",
  "Carol", "Moonlight", "Brokeback Mountain",
  "Blue Is the Warmest Colour", "Amour",
  "In the Mood for Love", "Amélie",
  "The Fault in Our Stars", "Me Before You", "Five Feet Apart",
  "A Star Is Born", "A Star Is Born (2018)",
  "Past Lives", "Normal People", "Aftersun",
  "All of Us Strangers", "Challengers", "We Live in Time",
  "Anyone But You", "Red, White & Royal Blue",
  "Bridget Jones's Diary", "Bridget Jones: The Edge of Reason",
  "Bridget Jones's Baby",
  "The Princess Bride", "Stardust", "Enchanted",
  "Titanic", "Ghost", "Dirty Dancing",

  // Crime & Gangster
  "The Godfather", "The Godfather Part II", "The Godfather Part III",
  "Goodfellas", "Casino", "The Irishman",
  "Scarface", "The Untouchables", "A Bronx Tale",
  "Carlito's Way", "Donnie Brasco", "American Gangster",
  "Gangs of New York", "Public Enemies", "Road to Perdition",
  "Heat", "Collateral", "Thief", "Miami Vice",
  "The French Connection", "Serpico", "Dog Day Afternoon",
  "The Town", "Gone Baby Gone", "Mystic River",
  "Pulp Fiction", "Reservoir Dogs", "True Romance",
  "Natural Born Killers", "Jackie Brown",
  "Snatch", "Lock, Stock and Two Smoking Barrels",
  "RocknRolla", "The Gentlemen", "Wrath of Man",
  "Layer Cake", "Sexy Beast",
  "Fargo", "No Country for Old Men", "Blood Simple",
  "A Simple Plan", "Nightcrawler",
  "City of God", "Elite Squad", "Elite Squad: The Enemy Within",
  "Infernal Affairs", "The Departed",
  "Sicario", "Traffic", "Narcos",
  "Zodiac", "Prisoners", "Se7en",
  "Catch Me If You Can", "The Wolf of Wall Street",
  "American Hustle", "The Big Short",
  "Molly's Game", "Rounders", "The Cincinnati Kid",
  "Ocean's Eleven", "Ocean's Twelve", "Ocean's Thirteen",
  "Ocean's 8", "Now You See Me", "Now You See Me 2",
  "Baby Driver", "Drive", "Nightcrawler",
  "Uncut Gems", "Good Time",

  // War & Historical
  "Saving Private Ryan", "Schindler's List", "The Pianist",
  "Dunkirk", "1917", "Hacksaw Ridge",
  "Apocalypse Now", "Full Metal Jacket", "Platoon",
  "Born on the Fourth of July", "We Were Soldiers", "Hamburger Hill",
  "Black Hawk Down", "Lone Survivor", "American Sniper",
  "The Hurt Locker", "Zero Dark Thirty", "13 Hours",
  "Fury", "Inglourious Basterds", "Valkyrie",
  "The Imitation Game", "Darkest Hour", "The King's Speech",
  "Bridge of Spies", "The Spy Who Came in from the Cold",
  "All Quiet on the Western Front", "All Quiet on the Western Front (2022)",
  "Paths of Glory", "Come and See", "Das Boot",
  "The Thin Red Line", "Letters from Iwo Jima", "Flags of Our Fathers",
  "Braveheart", "Gladiator", "Kingdom of Heaven",
  "The Last Samurai", "Master and Commander: The Far Side of the World",
  "Troy", "Alexander", "Ben-Hur",
  "Lawrence of Arabia", "Doctor Zhivago", "Gandhi",
  "Lincoln", "Selma", "12 Years a Slave",
  "Hidden Figures", "The Color Purple",
  "Malcolm X", "Do the Right Thing", "BlacKkKlansman",
  "Judas and the Black Messiah", "One Night in Miami",
  "Harriet", "The Woman King",
  "Oppenheimer", "First Man", "The Right Stuff",
  "Apollo 13", "The Current War",
  "The Favourite", "Marie Antoinette", "Elizabeth",
  "The Other Boleyn Girl", "Atonement",
  "Emancipation", "The Revenant", "Killers of the Flower Moon",
  "Napoleon", "Civil War",

  // Sports Films
  "Rocky", "Rocky II", "Rocky III", "Rocky IV", "Rocky Balboa",
  "Creed", "Creed II", "Creed III",
  "Raging Bull", "The Fighter", "Million Dollar Baby",
  "Ali", "When We Were Kings",
  "Moneyball", "The Natural", "Field of Dreams",
  "A League of Their Own", "Major League", "Bull Durham",
  "42", "The Sandlot",
  "Remember the Titans", "Friday Night Lights", "The Blind Side",
  "Draft Day", "Any Given Sunday", "The Longest Yard",
  "Concussion", "Jerry Maguire",
  "Rush", "Ford v Ferrari", "Talladega Nights",
  "Days of Thunder", "Senna",
  "Hoosiers", "Coach Carter", "Space Jam",
  "White Men Can't Jump", "Hustle", "Air",
  "The Way Back", "King Richard",
  "I, Tonya", "Blades of Glory",
  "Foxcatcher", "Warrior", "The Wrestler",
  "Southpaw", "Cinderella Man",
  "Chariots of Fire", "Invictus", "Cool Runnings",
  "Eddie the Eagle", "McFarland, USA",
  "Challengers", "The Iron Claw",
  "Seabiscuit", "Secretariat", "War Horse",

  // Musicals
  "La La Land", "West Side Story", "West Side Story (2021)",
  "The Sound of Music", "Singin' in the Rain", "Grease",
  "Chicago", "Moulin Rouge!", "Les Misérables",
  "The Greatest Showman", "A Star Is Born", "A Star Is Born (2018)",
  "Into the Woods", "Sweeney Todd: The Demon Barber of Fleet Street",
  "Mamma Mia!", "Mamma Mia! Here We Go Again",
  "Hairspray", "Dreamgirls", "The Phantom of the Opera",
  "Rent", "In the Heights", "Dear Evan Hansen",
  "tick, tick... BOOM!", "Wonka", "Wicked",
  "Mean Girls (2024)", "The Color Purple (2023)",
  "Cats", "Annie", "Mary Poppins", "Mary Poppins Returns",
  "The Wizard of Oz", "Fiddler on the Roof",
  "Cabaret", "All That Jazz", "Funny Girl",
  "An American in Paris", "My Fair Lady",
  "Emilia Pérez",

  // Documentary (top 60)
  "March of the Penguins", "An Inconvenient Truth",
  "Fahrenheit 9/11", "Bowling for Columbine", "Sicko",
  "Blackfish", "The Cove", "Food, Inc.",
  "Inside Job", "The Big Short",
  "13th", "I Am Not Your Negro",
  "Free Solo", "The Dawn Wall",
  "Won't You Be My Neighbor?", "RBG",
  "Amy", "Senna", "Diego Maradona",
  "The Last Dance", "Tiger",
  "Jiro Dreams of Sushi", "Chef's Table",
  "My Octopus Teacher", "Fantastic Fungi",
  "The Act of Killing", "The Look of Silence",
  "Citizenfour", "The Social Dilemma",
  "The Great Hack", "Coded Bias",
  "Making a Murderer", "The Staircase",
  "Wild Wild Country", "The Jinx",
  "Icarus", "Collective",
  "Summer of Soul", "Moonage Daydream",
  "All the Beauty and the Bloodshed",
  "Fire of Love", "Navalny",
  "20 Days in Mariupol", "Sugarcane",
  "Super Size Me", "Exit Through the Gift Shop",
  "Man on Wire", "Searching for Sugar Man",
  "Planet Earth", "Planet Earth II", "Blue Planet II",
  "Our Planet",
  "Hamilton", "Stop Making Sense",
  "This Is It", "Woodstock",
  "The Beatles: Get Back",
  "The Fog of War", "Shoah", "Night and Fog",
  "Grizzly Man", "Cave of Forgotten Dreams", "Into the Abyss",
  "Hoop Dreams", "O.J.: Made in America",
  "They Shall Not Grow Old", "Apollo 11",
  "The Biggest Little Farm", "Kiss the Ground",
  "Seaspiracy", "Cowspiracy", "Forks Over Knives",
  "The Game Changers", "What the Health",
  "Tiger King", "The Tinder Swindler",
  "Don't F**k with Cats", "The Keepers",
  "Three Identical Strangers", "Dear Zachary",
  "Paris Is Burning", "Tongues Untied",
  "Crip Camp", "Time", "Flee",
  "Ascension", "All the Beauty and the Bloodshed",
  "Restrepo", "Cartel Land", "City of Ghosts",
  "The Square (2013)", "For Sama",
  "Honeyland", "The Cave", "Virunga",
  "Miss Americana", "Billie Eilish: The World's a Little Blurry",
  "Madonna: Truth or Dare", "Gimme Shelter",
  "The Last Waltz", "Buena Vista Social Club",
  "Anvil! The Story of Anvil", "Metallica: Some Kind of Monster",

  // Additional Comedy
  "Coming to America", "Coming 2 America",
  "Trading Places", "48 Hrs.",
  "Blazing Saddles", "Young Frankenstein", "Spaceballs", "History of the World, Part I",
  "Airplane!", "The Naked Gun", "Top Secret!",
  "Dr. Strangelove", "Being There", "The Producers",
  "Annie Hall", "Manhattan", "Midnight in Paris",
  "What About Bob?", "Groundhog Day", "Lost in Translation",
  "The Breakfast Club", "Sixteen Candles", "Weird Science",
  "Better Off Dead", "Say Anything...",
  "Caddyshack", "Animal House", "Old School",
  "Road Trip", "EuroTrip", "Van Wilder",
  "American Pie", "American Pie 2", "American Wedding",
  "White Chicks", "Scary Movie", "Date Movie",
  "Shaun of the Dead", "Hot Fuzz", "The World's End",
  "What We Do in the Shadows", "Thor: Ragnarok",
  "Juno", "Little Miss Sunshine", "The Way Way Back",
  "The Perks of Being a Wallflower", "The Spectacular Now",
  "Me and Earl and the Dying Girl", "Eighth Grade",
  "Bo Burnham: Inside", "Hannah Gadsby: Nanette",
  "Borat", "Bruno", "The Dictator",
  "Sacha Baron Cohen", "Jackass Forever",
  "Bad Santa", "Bad Teacher", "Bad Moms",
  "Horrible Bosses 2", "Identity Thief",
  "The Internship", "Unfinished Business",
  "Tag", "Blockers", "Good Boys",
  "Booksmart", "Bottoms", "Theater Camp",
  "Palm Springs", "The Map of Tiny Perfect Things",
  "Long Shot", "Isn't It Romantic", "Plus One",
  "Always Be My Maybe", "Crazy Rich Asians",
  "Bros", "Fire Island", "Spoiler Alert",
  "Glass Onion", "See How They Run",
  "The Unbearable Weight of Massive Talent",
  "Bullet Train", "The Lost City",

  // Additional Romance
  "Casablanca", "An Affair to Remember", "Roman Holiday",
  "Breakfast at Tiffany's", "West Side Story",
  "The Way We Were", "Love Story",
  "Annie Hall", "When Harry Met Sally",
  "Say Anything...", "Pretty in Pink", "Sixteen Candles",
  "Four Weddings and a Funeral", "Sense and Sensibility",
  "Pride and Prejudice", "Pride and Prejudice (2005)",
  "Emma", "Emma (2020)", "Persuasion",
  "Jane Eyre", "Wuthering Heights",
  "Atonement", "The English Patient",
  "The Bridges of Madison County", "Out of Africa",
  "Doctor Zhivago", "A Room with a View",
  "Shakespeare in Love", "Becoming Jane",
  "The Age of Innocence", "The Phantom Thread",
  "Moonrise Kingdom", "Harold and Maude",
  "Punch-Drunk Love", "Her",
  "Ruby Sparks", "Lars and the Real Girl",
  "Warm Bodies", "About Time",
  "The Vow", "Remember Me", "Safe Haven",
  "P.S. I Love You", "Letters to Juliet",
  "The Lucky One", "The Choice",
  "Crazy, Stupid, Love", "Just Friends",
  "Forgetting Sarah Marshall", "The Five-Year Engagement",
  "Dating Around", "Love, Simon",
  "Moonlight", "Call Me by Your Name",
  "Portrait of a Lady on Fire", "Disobedience",
  "The Handmaiden", "Blue Is the Warmest Colour",
  "Carol", "Ammonite",
  "Brokeback Mountain", "Milk", "Dallas Buyers Club",

  // Additional Crime
  "The Departed", "Infernal Affairs",
  "A Prophet", "Gomorrah",
  "The Godfather Part III", "Once Upon a Time in America",
  "Miller's Crossing", "Road to Perdition",
  "Eastern Promises", "A History of Violence",
  "The French Connection", "The French Connection II",
  "The Untouchables", "L.A. Confidential",
  "Chinatown", "Mulholland Drive",
  "Inherent Vice", "The Long Goodbye",
  "The Big Sleep", "Double Indemnity",
  "Sunset Boulevard", "Mildred Pierce",
  "Body Heat", "Blood Simple",
  "Bound", "The Grifters",
  "Primal Fear", "Presumed Innocent",
  "A Few Good Men", "The Firm",
  "Michael Clayton", "The Lincoln Lawyer",
  "Erin Brockovich", "Dark Waters",
  "Spotlight", "All the President's Men",
  "The Post", "The Insider",
  "Zodiac", "Memories of Murder",
  "The Chaser", "Oldboy",
  "Marshland", "The Secret in Their Eyes",

  // Additional War/Historical
  "Tora! Tora! Tora!", "Midway", "The Longest Day",
  "A Bridge Too Far", "The Great Escape",
  "Kelly's Heroes", "Where Eagles Dare",
  "The Dirty Dozen", "Stalag 17",
  "From Here to Eternity", "The Guns of Navarone",
  "The Battle of Algiers", "Waltz with Bashir",
  "Beasts of No Nation", "Hotel Rwanda",
  "The Killing Fields", "The Year of Living Dangerously",
  "Tears of the Sun", "Blood Diamond",
  "The Last King of Scotland", "Idi Amin",
  "The Constant Gardener", "Eye in the Sky",
  "Son of Saul", "Life Is Beautiful",
  "The Boy in the Striped Pyjamas", "Sophie's Choice",
  "The Reader", "Sarah's Key",
  "Defiance", "Resistance",
  "Anthropoid", "Operation Mincemeat",
  "The Monuments Men", "Woman in Gold",
  "Darkest Hour", "Their Finest",
  "Dunkirk", "Midway (2019)",
  "Greyhound", "The Outpost",
  "Cherry", "The Yellow Birds",
  "Restrepo", "Korengal",
  "The Hurt Locker", "Brothers",
  "The Messenger", "Thank You for Your Service",
];

// ─── BATCH 5: Director Filmographies, International, Cult, 2024-2026 ───────

export const BATCH_5: string[] = [
  // Christopher Nolan (complete)
  "Following", "Memento", "Insomnia", "Batman Begins",
  "The Prestige", "The Dark Knight", "Inception",
  "The Dark Knight Rises", "Interstellar", "Dunkirk",
  "Tenet", "Oppenheimer",

  // Quentin Tarantino (complete)
  "Reservoir Dogs", "Pulp Fiction", "Jackie Brown",
  "Kill Bill: Vol. 1", "Kill Bill: Vol. 2", "Death Proof",
  "Inglourious Basterds", "Django Unchained", "The Hateful Eight",
  "Once Upon a Time in Hollywood",

  // Martin Scorsese (major works)
  "Mean Streets", "Taxi Driver", "Raging Bull", "The King of Comedy",
  "After Hours", "The Color of Money", "The Last Temptation of Christ",
  "Goodfellas", "Cape Fear", "The Age of Innocence",
  "Casino", "Kundun", "Bringing Out the Dead",
  "Gangs of New York", "The Aviator", "The Departed",
  "Shutter Island", "Hugo", "The Wolf of Wall Street",
  "Silence", "The Irishman", "Killers of the Flower Moon",

  // Steven Spielberg (major works)
  "Jaws", "Close Encounters of the Third Kind", "Raiders of the Lost Ark",
  "E.T. the Extra-Terrestrial", "Indiana Jones and the Temple of Doom",
  "The Color Purple", "Empire of the Sun",
  "Indiana Jones and the Last Crusade", "Schindler's List",
  "Jurassic Park", "Amistad", "Saving Private Ryan",
  "A.I. Artificial Intelligence", "Minority Report", "Catch Me If You Can",
  "The Terminal", "War of the Worlds", "Munich",
  "Lincoln", "Bridge of Spies", "The BFG",
  "Ready Player One", "West Side Story", "The Fabelmans",

  // Denis Villeneuve (complete)
  "Incendies", "Prisoners", "Enemy", "Sicario",
  "Arrival", "Blade Runner 2049", "Dune", "Dune: Part Two",

  // David Fincher (complete)
  "Alien 3", "Se7en", "The Game", "Fight Club",
  "Panic Room", "Zodiac", "The Curious Case of Benjamin Button",
  "The Social Network", "The Girl with the Dragon Tattoo",
  "Gone Girl", "Mank", "The Killer",

  // Paul Thomas Anderson (complete)
  "Hard Eight", "Boogie Nights", "Magnolia",
  "Punch-Drunk Love", "There Will Be Blood",
  "The Master", "Inherent Vice", "Phantom Thread", "Licorice Pizza",

  // Coen Brothers (major works)
  "Blood Simple", "Raising Arizona", "Miller's Crossing",
  "Barton Fink", "The Hudsucker Proxy", "Fargo",
  "The Big Lebowski", "O Brother, Where Art Thou?",
  "No Country for Old Men", "Burn After Reading", "A Serious Man",
  "True Grit", "Inside Llewyn Davis", "Hail, Caesar!",
  "The Ballad of Buster Scruggs",

  // Stanley Kubrick (complete features)
  "Paths of Glory", "Spartacus", "Lolita",
  "Dr. Strangelove", "2001: A Space Odyssey", "A Clockwork Orange",
  "Barry Lyndon", "The Shining", "Full Metal Jacket", "Eyes Wide Shut",

  // Wes Anderson (complete)
  "Bottle Rocket", "Rushmore", "The Royal Tenenbaums",
  "The Life Aquatic with Steve Zissou", "The Darjeeling Limited",
  "Fantastic Mr. Fox", "Moonrise Kingdom", "The Grand Budapest Hotel",
  "Isle of Dogs", "The French Dispatch", "Asteroid City",

  // Ridley Scott (major works)
  "Alien", "Blade Runner", "Thelma & Louise",
  "Gladiator", "Black Hawk Down", "Kingdom of Heaven",
  "American Gangster", "Robin Hood", "The Martian",
  "The Last Duel", "House of Gucci", "Napoleon", "Gladiator II",

  // James Cameron (complete)
  "The Terminator", "Aliens", "The Abyss", "Terminator 2: Judgment Day",
  "True Lies", "Titanic", "Avatar", "Avatar: The Way of Water",

  // Damien Chazelle
  "Whiplash", "La La Land", "First Man", "Babylon",

  // Jordan Peele
  "Get Out", "Us", "Nope",

  // Greta Gerwig
  "Lady Bird", "Little Women", "Barbie",

  // Bong Joon-ho
  "Memories of Murder", "The Host", "Mother",
  "Snowpiercer", "Okja", "Parasite", "Mickey 17",

  // Park Chan-wook
  "Oldboy", "Sympathy for Mr. Vengeance", "Lady Vengeance",
  "Thirst", "The Handmaiden", "Decision to Leave",

  // Wong Kar-wai
  "Chungking Express", "Fallen Angels", "Happy Together",
  "In the Mood for Love", "2046", "The Grandmaster",

  // Alfonso Cuarón
  "Y Tu Mamá También", "Harry Potter and the Prisoner of Azkaban",
  "Children of Men", "Gravity", "Roma",

  // Guillermo del Toro
  "Cronos", "The Devil's Backbone", "Blade II",
  "Hellboy", "Hellboy II: The Golden Army",
  "Pan's Labyrinth", "Pacific Rim", "Crimson Peak",
  "The Shape of Water", "Nightmare Alley",
  "Guillermo del Toro's Pinocchio",

  // Alejandro González Iñárritu
  "Amores Perros", "21 Grams", "Babel",
  "Biutiful", "Birdman", "The Revenant",

  // Spike Lee (major works)
  "She's Gotta Have It", "Do the Right Thing", "Malcolm X",
  "25th Hour", "Inside Man", "BlacKkKlansman", "Da 5 Bloods",

  // Akira Kurosawa (major works)
  "Rashomon", "Ikiru", "Seven Samurai", "Throne of Blood",
  "The Hidden Fortress", "Yojimbo", "Sanjuro",
  "High and Low", "Red Beard", "Dersu Uzala",
  "Kagemusha", "Ran", "Dreams",

  // David Lynch (major works)
  "Eraserhead", "The Elephant Man", "Blue Velvet",
  "Wild at Heart", "Lost Highway", "The Straight Story",
  "Mulholland Drive", "Inland Empire",

  // Terrence Malick (major works)
  "Badlands", "Days of Heaven", "The Thin Red Line",
  "The New World", "The Tree of Life", "Knight of Cups",

  // Pedro Almodóvar (major works)
  "Women on the Verge of a Nervous Breakdown", "Tie Me Up! Tie Me Down!",
  "All About My Mother", "Talk to Her", "Volver",
  "The Skin I Live In", "Pain and Glory", "Parallel Mothers",
  "The Room Next Door",

  // Lars von Trier (major works)
  "Breaking the Waves", "Dancer in the Dark", "Dogville",
  "Melancholia", "Nymphomaniac", "The House That Jack Built",

  // Michael Mann (major works)
  "Thief", "Manhunter", "The Last of the Mohicans",
  "Heat", "The Insider", "Collateral",
  "Miami Vice", "Public Enemies", "Ferrari",

  // Clint Eastwood (major directing works)
  "Unforgiven", "Mystic River", "Million Dollar Baby",
  "Letters from Iwo Jima", "Gran Torino", "Invictus",
  "American Sniper", "Sully", "Richard Jewell", "Juror #2",

  // Tim Burton (major works)
  "Beetlejuice", "Batman", "Edward Scissorhands",
  "Batman Returns", "Ed Wood", "Sleepy Hollow",
  "Big Fish", "Charlie and the Chocolate Factory",
  "Sweeney Todd: The Demon Barber of Fleet Street",
  "Alice in Wonderland", "Beetlejuice Beetlejuice",

  // Sofia Coppola
  "The Virgin Suicides", "Lost in Translation", "Marie Antoinette",
  "Somewhere", "The Bling Ring", "The Beguiled", "Priscilla",

  // Yorgos Lanthimos
  "Dogtooth", "The Lobster", "The Killing of a Sacred Deer",
  "The Favourite", "Poor Things", "Kinds of Kindness",

  // Robert Eggers
  "The Witch", "The Lighthouse", "The Northman", "Nosferatu",

  // Sean Baker
  "Tangerine", "The Florida Project", "Red Rocket", "Anora",

  // Edgar Wright
  "Shaun of the Dead", "Hot Fuzz", "Scott Pilgrim vs. the World",
  "The World's End", "Baby Driver", "Last Night in Soho",

  // Taika Waititi
  "Boy", "What We Do in the Shadows", "Hunt for the Wilderpeople",
  "Thor: Ragnarok", "Jojo Rabbit", "Thor: Love and Thunder",
  "Next Goal Wins",

  // Danny Boyle
  "Shallow Grave", "Trainspotting", "28 Days Later",
  "Slumdog Millionaire", "127 Hours", "Steve Jobs",
  "T2 Trainspotting", "Yesterday",

  // Sam Raimi
  "The Evil Dead", "Evil Dead II", "Army of Darkness",
  "A Simple Plan", "Spider-Man", "Spider-Man 2", "Spider-Man 3",
  "Drag Me to Hell",

  // Kathryn Bigelow
  "Point Break", "Strange Days", "The Hurt Locker",
  "Zero Dark Thirty", "Detroit",

  // Barry Jenkins
  "Moonlight", "If Beale Street Could Talk", "Mufasa: The Lion King",

  // Rian Johnson
  "Brick", "Looper", "Star Wars: The Last Jedi",
  "Knives Out", "Glass Onion",

  // Christopher Guest
  "This Is Spinal Tap", "Waiting for Guffman",
  "Best in Show", "A Mighty Wind", "For Your Consideration",

  // International Cinema — Korean (top 50)
  "Parasite", "Oldboy", "Memories of Murder",
  "The Handmaiden", "Train to Busan", "I Saw the Devil",
  "The Wailing", "A Taxi Driver", "Burning",
  "Decision to Leave", "The Host", "Mother",
  "Snowpiercer", "A Tale of Two Sisters", "Sympathy for Mr. Vengeance",
  "Lady Vengeance", "Joint Security Area", "Silenced",
  "Poetry", "Spring, Summer, Fall, Winter... and Spring",
  "Pieta", "Secret Sunshine", "Oasis",
  "The Man from Nowhere", "New World", "A Hard Day",
  "The Gangster, the Cop, the Devil", "Extreme Job",
  "Broker", "Past Lives", "Minari",
  "Exhuma", "Emergency Declaration", "Escape from Mogadishu",
  "The Admiral: Roaring Currents", "Along with the Gods",
  "Masquerade", "The Thieves", "Veteran",
  "Miracle in Cell No. 7", "My Sassy Girl",
  "Castaway on the Moon", "The Good, the Bad, the Weird",
  "Peppermint Candy", "The Chaser", "A Bittersweet Life",
  "The Yellow Sea", "Bedevilled", "Thirst",
  "Hansel and Gretel", "Save the Green Planet!",

  // International Cinema — Japanese (top 50)
  "Rashomon", "Seven Samurai", "Tokyo Story",
  "Spirited Away", "Your Name", "Akira",
  "Ghost in the Shell", "Princess Mononoke", "My Neighbor Totoro",
  "Grave of the Fireflies", "Howl's Moving Castle", "The Boy and the Heron",
  "Shoplifters", "Drive My Car", "Departures",
  "Ringu", "Audition", "Battle Royale",
  "Harakiri", "Yojimbo", "Ikiru",
  "Ran", "Kagemusha", "High and Low",
  "In the Realm of the Senses", "Woman in the Dunes",
  "Tampopo", "Shall We Dance?",
  "13 Assassins", "Blade of the Immortal",
  "Suzume", "Weathering with You", "The First Slam Dunk",
  "Demon Slayer: Mugen Train", "Perfect Blue", "Paprika",
  "The Wind Rises", "Godzilla Minus One",
  "Monster", "Evil Does Not Exist",
  "Cure", "Pulse", "Dark Water",
  "Confessions", "Villain", "Like Father, Like Son",
  "The Taste of Tea", "Nobody Knows", "Still Walking",
  "After the Storm", "Our Little Sister",

  // International Cinema — Indian/Bollywood (top 50)
  "3 Idiots", "Dangal", "PK", "Lagaan",
  "Baahubali: The Beginning", "Baahubali 2: The Conclusion",
  "RRR", "KGF: Chapter 1", "KGF: Chapter 2",
  "Dil Chahta Hai", "Zindagi Na Milegi Dobara",
  "Gangs of Wasseypur", "Gangs of Wasseypur – Part 2",
  "Rang De Basanti", "Swades", "Taare Zameen Par",
  "Like Stars on Earth", "Queen",
  "Andhadhun", "Article 15", "Tumbbad",
  "Drishyam", "Drishyam 2",
  "Pushpa: The Rise", "Pushpa: The Rule",
  "Pathaan", "Jawan", "Animal",
  "Kantara", "Vikram", "Jai Bhim",
  "The Lunchbox", "Pather Panchali", "Satyajit Ray's Apu Trilogy",
  "Salaam Bombay!", "Monsoon Wedding",
  "Slumdog Millionaire", "Lion", "Life of Pi",
  "The White Tiger", "All We Imagine as Light",
  "Dilwale Dulhania Le Jayenge", "Kabhi Khushi Kabhie Gham",
  "Sholay", "Mughal-e-Azam", "Mother India",
  "Devdas", "Devdas (2002)", "Rang De Basanti",
  "Chak De! India", "Bhaag Milkha Bhaag",
  "Bajrangi Bhaijaan", "Secret Superstar",
  "Gully Boy", "The Sky Is Pink",
  "Chhichhore", "Stree", "Stree 2",

  // International Cinema — French (top 30)
  "Amélie", "The Intouchables", "Blue Is the Warmest Colour",
  "La Haine", "Caché", "The Class",
  "A Prophet", "Portrait of a Lady on Fire", "Anatomy of a Fall",
  "The Artist", "Amour", "Persepolis",
  "Raw", "Titane", "The Taste of Things",
  "Les Misérables (2019)", "Dheepan", "The Diving Bell and the Butterfly",
  "Breathless", "The 400 Blows", "Jules and Jim",
  "The Umbrellas of Cherbourg", "Léon: The Professional",
  "Tell No One", "Emilia Pérez",
  "The Wages of Fear", "Rififi", "Le Samouraï",
  "Army of Shadows", "The Battle of Algiers",
  "Jean de Florette", "Manon of the Spring",
  "Delicatessen", "The City of Lost Children",
  "Three Colors: Blue", "Three Colors: White", "Three Colors: Red",
  "La Femme Nikita", "The Fifth Element",
  "Irréversible", "Enter the Void", "Climax",
  "Holy Motors", "The Piano Teacher",
  "White Material", "35 Shots of Rum",

  // International Cinema — Spanish/Latin American (top 25)
  "Pan's Labyrinth", "The Secret in Their Eyes", "Amores Perros",
  "Y Tu Mamá También", "Roma", "All About My Mother",
  "Talk to Her", "Volver", "Pain and Glory",
  "The Orphanage", "Wild Tales", "The Motorcycle Diaries",
  "City of God", "Elite Squad", "Capernaum",
  "A Fantastic Woman", "The Platform", "I'm Still Here",
  "Society of the Snow",
  "The Spirit of the Beehive", "Viridiana", "Belle Époque",
  "Open Your Eyes", "The Others",
  "Rec", "Julia's Eyes", "[REC]³: Genesis",
  "The Skin I Live In", "Julieta",
  "The Invisible Guest", "The Body",
  "Bacurau", "Aquarius", "The Second Mother",
  "Central Station", "Black Orpheus",

  // International Cinema — German/Scandinavian (expanded)
  "The Lives of Others", "Das Boot", "Downfall",
  "Run Lola Run", "Good Bye, Lenin!", "The White Ribbon",
  "All Quiet on the Western Front (2022)", "The Zone of Interest",
  "Toni Erdmann",
  "The Girl with the Dragon Tattoo (2009)", "Let the Right One In",
  "The Square", "Force Majeure", "Another Round",
  "The Hunt", "A Royal Affair", "The Worst Person in the World",
  "Nymphomaniac", "Melancholia", "Dancer in the Dark",
  "The Celebration", "After the Wedding", "A War",
  "The Guilty (2018)", "Riders of Justice",
  "Headhunters", "The Wave", "Thelma",
  "Border", "The 100-Year-Old Man Who Climbed Out the Window and Disappeared",
  "Nostalgia for the Light", "The Tin Drum",
  "Wings of Desire", "The Marriage of Maria Braun",
  "M", "Metropolis", "The Cabinet of Dr. Caligari",
  "Nosferatu (1922)", "Aguirre, the Wrath of God",
  "Fitzcarraldo", "The Enigma of Kaspar Hauser",

  // International Cinema — Chinese/East Asian (expanded)
  "Crouching Tiger, Hidden Dragon", "Hero", "House of Flying Daggers",
  "In the Mood for Love", "Chungking Express", "Farewell My Concubine",
  "Raise the Red Lantern", "To Live",
  "Lust, Caution", "The Flowers of War", "Shadow",
  "Still Life", "A Touch of Sin",
  "Long Day's Journey into Night", "So Long, My Son",
  "Infernal Affairs", "A Better Tomorrow",
  "The Killer", "Hard Boiled", "A Chinese Ghost Story",
  "Kung Fu Hustle", "Shaolin Soccer",
  "Ip Man", "Ip Man 2", "Ip Man 3", "Ip Man 4",
  "The Grandmaster", "Yi Yi", "A Brighter Summer Day",
  "A City of Sadness", "The Assassin",
  "Happy Together", "Fallen Angels", "2046",
  "Drunken Master", "Police Story",
  "Coming Home", "The Road Home",
  "Spring in a Small Town", "Platform",

  // International Cinema — Iranian/Middle Eastern
  "A Separation", "The Salesman", "About Elly",
  "Close-Up", "Taste of Cherry", "The Wind Will Carry Us",
  "Panahi's Taxi", "No Bears", "The White Balloon",
  "Children of Heaven", "The Color of Paradise",
  "Persepolis", "Capernaum",
  "The Band's Visit", "Foxtrot", "Waltz with Bashir",

  // International Cinema — African/Other
  "Timbuktu", "Atlantics", "Dahomey",
  "Tsotsi", "District 9",
  "The Gods Must Be Crazy", "Vaya",
  "Uncle Boonmee Who Can Recall His Past Lives",
  "Tropical Malady", "Cemetery of Splendour",
  "The Act of Killing", "The Look of Silence",
  "Son of Saul", "Ida", "Cold War",
  "Loving Vincent", "The Painted Bird",
  "Lamb", "Difret",

  // International Cinema — Australian/New Zealand
  "Mad Max", "Mad Max 2: The Road Warrior",
  "Priscilla, Queen of the Desert", "Strictly Ballroom",
  "Muriel's Wedding", "The Dressmaker",
  "Animal Kingdom", "The Proposition",
  "Picnic at Hanging Rock", "Gallipoli",
  "The Piano", "Hunt for the Wilderpeople",
  "Once Were Warriors", "Boy",
  "What We Do in the Shadows", "Whale Rider",
  "The Babadook", "The Nightingale",
  "True History of the Kelly Gang", "Nitram",

  // Cult Classics (expanded)
  "The Rocky Horror Picture Show", "Donnie Darko", "Fight Club",
  "A Clockwork Orange", "Eraserhead", "Blue Velvet",
  "Mulholland Drive", "The Big Lebowski", "Office Space",
  "Clerks", "Mallrats", "Chasing Amy", "Dogma",
  "Reservoir Dogs", "Pulp Fiction", "True Romance",
  "The Princess Bride", "This Is Spinal Tap",
  "Monty Python and the Holy Grail", "Monty Python's Life of Brian",
  "The Room", "Troll 2", "Plan 9 from Outer Space",
  "Sharknado", "The Wicker Man",
  "Blade Runner", "Brazil", "Dark City",
  "They Live", "RoboCop", "Starship Troopers",
  "Total Recall", "Escape from New York",
  "Akira", "Ghost in the Shell", "Battle Royale",
  "Oldboy", "Audition",
  "Napoleon Dynamite", "Idiocracy", "Scott Pilgrim vs. the World",
  "Heathers", "Beetlejuice", "Edward Scissorhands",
  "The Evil Dead", "Evil Dead II", "Army of Darkness",
  "Re-Animator", "Suspiria",
  "Trainspotting", "Requiem for a Dream",
  "American Psycho", "Fear and Loathing in Las Vegas",
  "The Warriors", "Escape from New York",
  "Logan's Run", "Soylent Green",
  "Repo Man", "Videodrome", "Scanners",
  "Phantom of the Paradise", "The Rocky Horror Picture Show",
  "The Adventures of Buckaroo Banzai", "Big Trouble in Little China",
  "Flash Gordon", "Barbarella",
  "Showgirls", "Glengarry Glen Ross",
  "Withnail and I", "The Commitments",
  "Swingers", "Dazed and Confused",
  "Waking Life", "Slacker", "Before Sunrise",
  "Pi", "Primer", "Coherence",
  "The Man from Earth", "Moon",
  "Cube", "The Platform", "Circle",
  "Memento", "Oldboy", "The Prestige",
  "Predestination", "Time Crimes",
  "Happiness", "Welcome to the Dollhouse",
  "Ghost World", "Enid",
  "Wet Hot American Summer",
  "Black Dynamite", "Kung Fury",
  "The Toxic Avenger", "Class of 1984",
  "Chopping Mall", "Killer Klowns from Outer Space",
  "Attack the Block", "Turbo Kid",

  // 2024-2026 Major Theatrical Releases
  "Oppenheimer", "Barbie", "Killers of the Flower Moon",
  "Poor Things", "The Zone of Interest", "Anatomy of a Fall",
  "Past Lives", "The Holdovers", "American Fiction",
  "Saltburn", "May December", "Dream Scenario",
  "Maestro", "The Color Purple (2023)", "Wonka",
  "Aquaman and the Lost Kingdom", "Wish", "The Boy and the Heron",
  // 2024
  "Dune: Part Two", "Inside Out 2", "Deadpool & Wolverine",
  "Furiosa: A Mad Max Saga", "Alien: Romulus",
  "The Substance", "Conclave", "The Brutalist",
  "Anora", "Emilia Pérez", "Wicked",
  "Gladiator II", "Moana 2", "A Complete Unknown",
  "Nosferatu", "Nickel Boys", "I'm Still Here",
  "Challengers", "Civil War", "Twisters",
  "The Fall Guy", "Beetlejuice Beetlejuice", "Joker: Folie à Deux",
  "Smile 2", "Terrifier 3", "Longlegs", "Late Night with the Devil",
  "The Wild Robot", "Transformers One", "Despicable Me 4",
  "Kingdom of the Planet of the Apes", "Godzilla x Kong: The New Empire",
  "A Quiet Place: Day One", "It Ends with Us", "Trap",
  "Megalopolis", "The Apprentice", "Saturday Night",
  "A Real Pain", "Sing Sing", "Hit Man",
  "Love Lies Bleeding", "Rebel Ridge", "Monkey Man",
  "Hundreds of Beavers", "Robot Dreams", "Flow",
  "Memoir of a Snail", "Look Back",
  "Beverly Hills Cop: Axel F", "Bad Boys: Ride or Die",
  // 2025
  "Mickey 17", "Mission: Impossible – The Final Reckoning",
  "Thunderbolts*", "The Fantastic Four: First Steps",
  "Superman", "Jurassic World Rebirth",
  "Avatar: Fire and Ash", "Wicked: For Good",
  "Ballerina", "28 Years Later", "The Bride",
  "Sinners", "Wake Up Dead Man", "Elio",
  "How to Train Your Dragon", "Lilo & Stitch",
  "Snow White", "Final Destination Bloodlines",
  "Karate Kid: Legends", "Flight Risk", "The Monkey",
  "Wolf Man", "Companion", "Dog Man",
  "Paddington in Peru", "Captain America: Brave New World",
  "Novocaine", "Black Bag", "The Electric State",
  "A Minecraft Movie", "Alto Knights",
  "Warfare", "Drop",
  // 2026
  "The Batman – Part II", "Avengers: Doomsday",
  "Toy Story 5", "Zootopia 2", "Ice Age 6",
  "Shrek 5",

  // Christmas / Holiday
  "Home Alone", "Home Alone 2: Lost in New York",
  "Elf", "The Polar Express", "A Christmas Story",
  "It's a Wonderful Life", "Miracle on 34th Street",
  "National Lampoon's Christmas Vacation",
  "The Santa Clause", "The Santa Clause 2",
  "How the Grinch Stole Christmas", "The Grinch",
  "Love Actually", "The Holiday", "Die Hard",
  "Gremlins", "Scrooged", "A Christmas Carol",
  "The Muppet Christmas Carol", "Klaus",
  "Last Christmas", "Happiest Season",

  // Fantasy — Lord of the Rings / Hobbit / Narnia
  "The Lord of the Rings: The Fellowship of the Ring",
  "The Lord of the Rings: The Two Towers",
  "The Lord of the Rings: The Return of the King",
  "The Hobbit: An Unexpected Journey", "The Hobbit: The Desolation of Smaug",
  "The Hobbit: The Battle of the Five Armies",
  "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
  "The Chronicles of Narnia: Prince Caspian",
  "The Chronicles of Narnia: The Voyage of the Dawn Treader",
  "Stardust", "The Princess Bride", "Willow",
  "Pan's Labyrinth", "The NeverEnding Story",
  "Labyrinth", "The Dark Crystal", "Legend",
  "Eragon", "Percy Jackson & the Olympians: The Lightning Thief",
  "Percy Jackson: Sea of Monsters",
  "Warcraft", "Dungeons & Dragons: Honor Among Thieves",

  // Western
  "The Good, the Bad and the Ugly", "Unforgiven",
  "Django Unchained", "The Hateful Eight",
  "No Country for Old Men", "True Grit", "True Grit (2010)",
  "Tombstone", "Wyatt Earp",
  "The Magnificent Seven", "The Magnificent Seven (2016)",
  "3:10 to Yuma", "3:10 to Yuma (2007)",
  "Butch Cassidy and the Sundance Kid",
  "Once Upon a Time in the West",
  "The Searchers", "Shane", "High Noon",
  "The Man Who Shot Liberty Valance", "Rio Bravo",
  "Dances with Wolves", "Open Range",
  "Bone Tomahawk", "The Revenant", "The Power of the Dog",
  "Old Henry", "News of the World",
  "The Sisters Brothers", "The Ballad of Buster Scruggs",
  "Hell or High Water", "Wind River",
  "Killers of the Flower Moon",

  // Poker / Gambling niche
  "Rounders", "Molly's Game", "The Cincinnati Kid",
  "Casino", "Casino Royale", "21",
  "The Sting", "Ocean's Eleven",

  // Additional Director Filmographies — Ridley Scott (extended)
  "The Duellists", "Someone to Watch Over Me", "1492: Conquest of Paradise",
  "G.I. Jane", "Hannibal", "Matchstick Men",
  "Body of Lies", "A Good Year", "The Counselor",
  "Exodus: Gods and Kings", "All the Money in the World",

  // Denis Villeneuve (extended)
  "Maelstrom", "Polytechnique",

  // M. Night Shyamalan
  "The Sixth Sense", "Unbreakable", "Signs",
  "The Village", "The Happening", "The Last Airbender",
  "Split", "Glass", "Old", "Knock at the Cabin", "Trap",

  // Guy Ritchie
  "Lock, Stock and Two Smoking Barrels", "Snatch", "Swept Away",
  "Revolver", "RocknRolla", "Sherlock Holmes",
  "Sherlock Holmes: A Game of Shadows", "The Man from U.N.C.L.E.",
  "King Arthur: Legend of the Sword", "Aladdin",
  "The Gentlemen", "Wrath of Man", "Operation Fortune",
  "The Covenant",

  // Darren Aronofsky
  "Pi", "Requiem for a Dream", "The Fountain",
  "The Wrestler", "Black Swan", "Noah",
  "mother!", "The Whale",

  // Alejandro González Iñárritu (extended)
  "Amores Perros", "21 Grams", "Babel",
  "Biutiful", "Birdman", "The Revenant",

  // Denis Villeneuve (extended)
  "Maelstrom", "Polytechnique",

  // Noah Baumbach
  "The Squid and the Whale", "Greenberg", "Frances Ha",
  "While We're Young", "The Meyerowitz Stories",
  "Marriage Story", "White Noise", "Barbie",

  // Alexander Payne
  "Election", "About Schmidt", "Sideways",
  "The Descendants", "Nebraska", "Downsizing", "The Holdovers",

  // Mike Leigh
  "Naked", "Secrets & Lies", "Topsy-Turvy",
  "Vera Drake", "Happy-Go-Lucky", "Another Year",
  "Mr. Turner", "Peterloo",

  // Ken Loach
  "Kes", "The Wind That Shakes the Barley",
  "I, Daniel Blake", "Sorry We Missed You",
  "The Old Oak",

  // Denis Villeneuve
  // (already covered above)

  // Wes Craven (horror master)
  "A Nightmare on Elm Street", "The Serpent and the Rainbow",
  "The People Under the Stairs", "Scream", "Scream 2",
  "Red Eye",

  // John Carpenter (horror/sci-fi master)
  "Halloween", "Escape from New York", "The Thing",
  "Christine", "Starman", "Big Trouble in Little China",
  "They Live", "In the Mouth of Madness",

  // James Wan
  "Saw", "Dead Silence", "Insidious",
  "The Conjuring", "Insidious: Chapter 2",
  "Furious 7", "The Conjuring 2", "Aquaman",
  "Malignant", "Aquaman and the Lost Kingdom",

  // Additional Classic Drama
  "Citizen Kane", "Casablanca", "Gone with the Wind",
  "It's a Wonderful Life", "Sunset Boulevard",
  "A Streetcar Named Desire", "On the Waterfront",
  "Rebel Without a Cause", "East of Eden",
  "The Bridge on the River Kwai", "Ben-Hur",
  "Spartacus", "To Kill a Mockingbird",
  "Doctor Zhivago", "The Graduate",
  "Butch Cassidy and the Sundance Kid", "Easy Rider",
  "Midnight Cowboy", "The French Connection",
  "Dog Day Afternoon", "Network", "All the President's Men",
  "Annie Hall", "Apocalypse Now", "Kramer vs. Kramer",
  "Ordinary People", "Gandhi", "Terms of Endearment",
  "Rain Man", "Born on the Fourth of July",
  "Dances with Wolves", "JFK", "Philadelphia",
  "Braveheart", "The English Patient",
  "Titanic", "American Beauty", "Traffic",
  "A Beautiful Mind", "The Hours",
  "Lost in Translation", "Eternal Sunshine of the Spotless Mind",
  "Crash", "Babel", "The Curious Case of Benjamin Button",
  "Slumdog Millionaire", "The Hurt Locker",
  "The King's Speech", "The Artist",
  "Argo", "12 Years a Slave", "Birdman",
  "Spotlight", "Moonlight", "The Shape of Water",
  "Green Book", "Parasite", "Nomadland",
  "CODA", "Everything Everywhere All at Once",
  "Oppenheimer",

  // Additional Family Films
  "Matilda", "Willy Wonka & the Chocolate Factory",
  "Charlie and the Chocolate Factory",
  "The Wizard of Oz", "Mary Poppins",
  "E.T. the Extra-Terrestrial", "Hook",
  "The Princess Bride", "Labyrinth",
  "The NeverEnding Story", "The Dark Crystal",
  "The Land Before Time", "An American Tail",
  "All Dogs Go to Heaven", "The Secret of NIMH",
  "Charlotte's Web", "Babe", "Babe: Pig in the City",
  "Stuart Little", "Stuart Little 2",
  "Space Jam", "Space Jam: A New Legacy",
  "Paddington", "Paddington 2", "Paddington in Peru",
  "A Dog's Purpose", "A Dog's Journey",
  "Marley & Me", "Old Yeller", "Homeward Bound",
  "Beethoven", "Air Bud",
  "Spy Kids", "Spy Kids 2", "Spy Kids 3-D",
  "The Karate Kid", "The Karate Kid Part II",
  "The Karate Kid (2010)", "Cobra Kai",
  "Jumanji", "Jumanji: Welcome to the Jungle",
  "Jumanji: The Next Level",
  "Hugo", "The BFG", "Matilda (2022)",
  "Wonka", "The Super Mario Bros. Movie",
  "Sonic the Hedgehog", "Sonic the Hedgehog 2", "Sonic the Hedgehog 3",
  "Detective Pikachu",
  "The Polar Express", "A Christmas Story",

  // Additional Sci-Fi/Fantasy TV-to-Film & Missing
  "Serenity", "Firefly",
  "Star Trek: The Motion Picture", "Star Trek II: The Wrath of Khan",
  "Star Trek III: The Search for Spock", "Star Trek IV: The Voyage Home",
  "Star Trek: First Contact", "Star Trek",
  "Star Trek Into Darkness", "Star Trek Beyond",
  "Dune", "Dune: Part Two",
  "The Hitchhiker's Guide to the Galaxy",
  "Ender's Game", "The Giver",
  "Divergent", "The Maze Runner",
  "Ready Player One", "The Creator",
  "Valerian and the City of a Thousand Planets",
  "Jupiter Ascending", "The Fifth Element",
  "The Abyss", "Waterworld", "The Postman",
  "Dredd", "Judge Dredd",
  "Demolition Man", "The Running Man",
  "Escape from L.A.", "Escape from New York",
  "RoboCop 2", "RoboCop 3",
  "I Am Legend", "The Omega Man",
  "Planet of the Apes (2001)",
  "War of the Worlds (2005)", "Independence Day",
  "Independence Day: Resurgence",
  "Pacific Rim", "Pacific Rim: Uprising",
  "Real Steel", "Chappie",
  "Alita: Battle Angel", "Ghost in the Shell (2017)",
  "Edge of Tomorrow", "Oblivion",
  "Snowpiercer", "Elysium",
  "The Wandering Earth", "The Wandering Earth 2",
  "Three-Body Problem",
  "Atlas", "I Am Mother", "Vivarium",
  "High Life", "Aniara", "Prospect",
  "Annihilation", "Ex Machina", "Upgrade",
  "M3GAN", "The Creator", "Atlas",

  // Additional Missing Blockbusters / Popular Films
  "Avatar", "Avatar: The Way of Water",
  "Titanic", "Frozen", "Frozen II",
  "The Lion King", "The Lion King (2019)",
  "Beauty and the Beast", "Beauty and the Beast (2017)",
  "Aladdin", "Aladdin (2019)",
  "The Jungle Book (2016)", "Mulan (2020)",
  "The Little Mermaid (2023)",
  "Cinderella (2015)", "Maleficent", "Maleficent: Mistress of Evil",
  "Cruella", "Jungle Cruise",
  "Raya and the Last Dragon", "Encanto",
  "Lightyear", "Turning Red",
  "Elemental", "Inside Out 2",
  "Wish", "Strange World",
  "Moana", "Moana 2",
  "Coco", "Soul", "Luca",
  "Onward",
  "Top Gun", "Top Gun: Maverick",
  "The Shawshank Redemption", "The Green Mile",
  "Forrest Gump", "Cast Away",
  "The Terminal", "Big", "Philadelphia",
  "Saving Private Ryan", "Road to Perdition",
  "Cloud Atlas", "The Da Vinci Code", "Angels & Demons",
  "Inferno", "The Polar Express",
  "A Man Called Otto", "News of the World",
  "Greyhound", "Finch", "Elvis",
  "Once Upon a Time in Hollywood",
  "The Hateful Eight", "Django Unchained",
  "Inglourious Basterds", "Kill Bill: Vol. 1",
  "Kill Bill: Vol. 2",

  // Additional 2025-2026 releases
  "The Monkey", "Companion", "Flight Risk",
  "Paddington in Peru", "Dog Man",
  "Captain America: Brave New World", "Novocaine",
  "Black Bag", "The Electric State",
  "A Minecraft Movie", "Alto Knights",
  "Warfare", "Drop", "Sinners",
  "Snow White", "Thunderbolts*",
  "Mission: Impossible – The Final Reckoning",
  "Karate Kid: Legends", "Lilo & Stitch",
  "The Fantastic Four: First Steps",
  "Jurassic World Rebirth", "Superman",
  "28 Years Later", "Wicked: For Good",
  "Avatar: Fire and Ash", "Elio",
  "Ballerina", "The Bride", "F1",
  "Wake Up Dead Man", "Materialists",
  "From the World of John Wick: Ballerina",
  "Brave New World", "Zootopia 2",
  "Toy Story 5", "The Batman – Part II",
  "Avengers: Doomsday", "Shrek 5",
  "Ice Age 6", "How to Train Your Dragon",
  "Final Destination Bloodlines",
  "Tron: Ares", "Blade",
  "The Running Man",
];

// ─── COMBINED EXPORT ─────────────────────────────────────────────────────────

// Supplemental titles to fill gaps across all decades and genres
export const SUPPLEMENTAL: string[] = [
  // 1970s Essential
  "The Godfather", "The Godfather Part II", "Jaws",
  "Star Wars: Episode IV - A New Hope", "Alien",
  "Rocky", "One Flew Over the Cuckoo's Nest",
  "Taxi Driver", "Apocalypse Now", "The Exorcist",
  "A Clockwork Orange", "The French Connection",
  "Chinatown", "Network", "Dog Day Afternoon",
  "All the President's Men", "Annie Hall",
  "Close Encounters of the Third Kind",
  "The Omen", "The Wicker Man", "Carrie",
  "Eraserhead", "Monty Python and the Holy Grail",
  "Willy Wonka & the Chocolate Factory",
  "The Rocky Horror Picture Show", "Barry Lyndon",
  "Serpico", "The Conversation",
  "Young Frankenstein", "Blazing Saddles",

  // 1980s Essential (gaps)
  "Raiders of the Lost Ark", "The Empire Strikes Back",
  "Return of the Jedi", "E.T. the Extra-Terrestrial",
  "Back to the Future", "The Shining",
  "Blade Runner", "Raging Bull", "Scarface",
  "Ferris Bueller's Day Off", "The Breakfast Club",
  "Sixteen Candles", "Pretty in Pink", "St. Elmo's Fire",
  "Dirty Dancing", "Footloose",
  "Flashdance", "Top Gun",
  "Beverly Hills Cop", "Coming to America",
  "Trading Places", "48 Hrs.",
  "Lethal Weapon", "Lethal Weapon 2",
  "Die Hard", "Predator", "RoboCop",
  "The Terminator", "Aliens",
  "Full Metal Jacket", "Platoon",
  "Stand by Me", "The Princess Bride",
  "Rain Man", "Amadeus",
  "Do the Right Thing", "Batman",
  "Ghostbusters", "Gremlins",
  "The Goonies", "Labyrinth",
  "The NeverEnding Story", "Willow",
  "Big", "Honey, I Shrunk the Kids",
  "Bill & Ted's Excellent Adventure",
  "When Harry Met Sally", "The Little Mermaid",
  "My Left Foot", "Dead Poets Society",
  "Glory", "Born on the Fourth of July",
  "Field of Dreams", "Major League",
  "Bull Durham", "The Natural",
  "Bloodsport", "Kickboxer",
  "Commando", "Rambo: First Blood Part II",
  "The Karate Kid", "The Fly",
  "An American Werewolf in London", "The Thing",
  "A Nightmare on Elm Street", "Friday the 13th",
  "Poltergeist", "Children of the Corn",
  "Pet Sematary", "Hellraiser",
  "Beetlejuice", "Heathers",
  "Say Anything...", "Broadcast News",
  "Moonstruck", "Tootsie",
  "The Color Purple", "Out of Africa",
  "Witness", "The Untouchables",
  "The Princess Bride", "Spaceballs",
  "Planes, Trains and Automobiles",
  "Scrooged", "Christmas Vacation",
  "Uncle Buck", "She's Having a Baby",

  // 1990s Essential (gaps)
  "Goodfellas", "The Silence of the Lambs", "Schindler's List",
  "Pulp Fiction", "Forrest Gump", "The Shawshank Redemption",
  "Fight Club", "The Matrix", "Se7en",
  "American Beauty", "The Sixth Sense",
  "Titanic", "Saving Private Ryan",
  "The Lion King", "Toy Story",
  "Jurassic Park", "Independence Day",
  "Men in Black", "Armageddon", "The Rock",
  "Con Air", "Face/Off", "The Mask",
  "Ace Ventura: Pet Detective", "Dumb and Dumber",
  "Liar Liar", "The Truman Show",
  "Jim Carrey", "Mrs. Doubtfire",
  "Groundhog Day", "Clueless", "10 Things I Hate About You",
  "American Pie", "There's Something About Mary",
  "Austin Powers: International Man of Mystery",
  "The Big Lebowski", "Fargo",
  "L.A. Confidential", "Heat",
  "Casino", "A Time to Kill",
  "The Fugitive", "The Firm",
  "A Few Good Men", "Philadelphia",
  "Sleepless in Seattle", "You've Got Mail",
  "My Best Friend's Wedding", "Pretty Woman",
  "Notting Hill", "Four Weddings and a Funeral",
  "Shakespeare in Love", "Sense and Sensibility",
  "Emma", "Pride and Prejudice",
  "Good Will Hunting", "Dead Poets Society",
  "The Talented Mr. Ripley", "Gattaca",
  "The Fifth Element", "Contact",
  "Event Horizon", "Dark City",
  "12 Monkeys", "Strange Days",
  "eXistenZ", "The Thirteenth Floor",
  "The Mummy", "The Mummy Returns",
  "Braveheart", "Gladiator", "The Patriot",
  "Saving Private Ryan",
  "The Thin Red Line", "Black Hawk Down",
  "The English Patient", "The Piano",
  "Trainspotting", "Lock, Stock and Two Smoking Barrels",
  "Guy Ritchie", "Snatch",
  "Run Lola Run", "Life Is Beautiful",
  "City of God", "Amélie",
  "Crouching Tiger, Hidden Dragon",
  "Hero", "The Matrix Reloaded",
  "Being John Malkovich", "Magnolia",
  "Boogie Nights", "Three Kings",
  "Office Space", "Election",
  "South Park: Bigger, Longer & Uncut",
  "Toy Story 2", "A Bug's Life",
  "Mulan", "Tarzan", "The Iron Giant",
  "The Prince of Egypt", "Antz",
  "Stuart Little", "Babe",
  "Free Willy", "Homeward Bound",
  "Hocus Pocus", "The Addams Family",
  "Addams Family Values",
  "Batman Returns", "Batman Forever",
  "Batman & Robin", "Spawn",
  "Blade", "Blade II",
  "The Crow", "Darkman",
  "Speed", "The Rock",
  "Mission: Impossible", "Twister",
  "Deep Impact", "Volcano",
  "Dante's Peak", "Outbreak",
  "The Negotiator", "Enemy of the State",
  "The Usual Suspects", "Primal Fear",
  "A Simple Plan", "Apt Pupil",
  "American History X", "American Psycho",
  "Eyes Wide Shut", "Magnolia",

  // 2000s Essential (gaps)
  "Gladiator", "Memento", "Requiem for a Dream",
  "Snatch", "O Brother, Where Art Thou?",
  "Almost Famous", "High Fidelity",
  "Cast Away", "Unbreakable",
  "Crouching Tiger, Hidden Dragon",
  "Billy Elliot", "Chocolat",
  "Erin Brockovich", "Traffic",
  "A Beautiful Mind", "The Lord of the Rings: The Fellowship of the Ring",
  "Black Hawk Down", "Training Day",
  "Monsters, Inc.", "Shrek", "Ice Age",
  "Spider-Man", "Harry Potter and the Sorcerer's Stone",
  "The Bourne Identity", "Minority Report",
  "Catch Me If You Can", "Road to Perdition",
  "Gangs of New York", "The Pianist",
  "City of God", "28 Days Later",
  "Finding Nemo", "Pirates of the Caribbean: The Curse of the Black Pearl",
  "Kill Bill: Vol. 1", "Lost in Translation",
  "Master and Commander: The Far Side of the World",
  "Mystic River", "Big Fish",
  "School of Rock", "Elf",
  "Eternal Sunshine of the Spotless Mind",
  "The Incredibles", "Spider-Man 2",
  "Shrek 2", "Harry Potter and the Prisoner of Azkaban",
  "Collateral", "The Aviator",
  "Million Dollar Baby", "Sideways",
  "Napoleon Dynamite", "Mean Girls",
  "Dodgeball", "Anchorman",
  "Shaun of the Dead", "Hotel Rwanda",
  "Batman Begins", "Sin City",
  "War of the Worlds", "Munich",
  "Brokeback Mountain", "Crash",
  "Walk the Line", "The 40-Year-Old Virgin",
  "Wedding Crashers", "Hustle & Flow",
  "V for Vendetta", "Casino Royale",
  "The Departed", "Pan's Labyrinth",
  "Children of Men", "Babel",
  "Little Miss Sunshine", "The Pursuit of Happyness",
  "Borat", "Cars", "Happy Feet",
  "Blood Diamond", "Dreamgirls",
  "Apocalypto", "The Lives of Others",
  "No Country for Old Men", "There Will Be Blood",
  "Juno", "Superbad", "Knocked Up",
  "Ratatouille", "Transformers",
  "The Bourne Ultimatum", "300",
  "I Am Legend", "Sweeney Todd",
  "Atonement", "Michael Clayton",
  "The Dark Knight", "WALL·E", "Iron Man",
  "Slumdog Millionaire", "Kung Fu Panda",
  "Step Brothers", "Tropic Thunder",
  "The Curious Case of Benjamin Button",
  "Milk", "The Wrestler",
  "Frost/Nixon", "The Reader",
  "In Bruges", "Taken", "Cloverfield",
  "The Hurt Locker", "Inglourious Basterds",
  "Avatar", "Up", "District 9",
  "Star Trek", "The Hangover",
  "Zombieland", "500 Days of Summer",
  "Fantastic Mr. Fox", "Coraline",
  "The Blind Side", "Precious",
  "A Serious Man", "An Education",

  // 2010s Essential (gaps)
  "Inception", "The Social Network", "Toy Story 3",
  "Black Swan", "The King's Speech",
  "True Grit", "127 Hours", "The Fighter",
  "The Artist", "Drive", "Moneyball",
  "Midnight in Paris", "The Help",
  "Hugo", "The Descendants",
  "Bridesmaids", "Fast Five",
  "The Dark Knight Rises", "The Avengers",
  "Django Unchained", "Argo",
  "Silver Linings Playbook", "Life of Pi",
  "Les Misérables", "Zero Dark Thirty",
  "Lincoln", "Beasts of the Southern Wild",
  "Gravity", "12 Years a Slave",
  "American Hustle", "The Wolf of Wall Street",
  "Her", "Dallas Buyers Club",
  "Captain Phillips", "Frozen",
  "The Hunger Games: Catching Fire",
  "Birdman", "Boyhood", "Whiplash",
  "The Grand Budapest Hotel", "The Imitation Game",
  "Gone Girl", "Interstellar",
  "Guardians of the Galaxy", "Nightcrawler",
  "John Wick", "The Lego Movie",
  "Selma", "Kingsman: The Secret Service",
  "Furious 7", "Avengers: Age of Ultron",
  "Mad Max: Fury Road", "The Revenant",
  "The Big Short", "The Martian",
  "Room", "Spotlight", "Bridge of Spies",
  "Star Wars: The Force Awakens",
  "Inside Out", "Sicario",
  "Ex Machina", "It Follows", "Creed",
  "La La Land", "Moonlight", "Arrival",
  "Manchester by the Sea", "Hell or High Water",
  "Lion", "Hidden Figures", "Fences",
  "Get Out", "Dunkirk", "Baby Driver",
  "Spider-Man: Homecoming", "Wonder Woman",
  "Logan", "Thor: Ragnarok",
  "The Shape of Water", "Three Billboards Outside Ebbing, Missouri",
  "Lady Bird", "Call Me by Your Name",
  "Phantom Thread", "I, Tonya",
  "Coco", "The Disaster Artist",
  "Black Panther", "Avengers: Infinity War",
  "A Quiet Place", "Hereditary",
  "Bohemian Rhapsody", "A Star Is Born",
  "Green Book", "Roma",
  "If Beale Street Could Talk", "Vice",
  "Spider-Man: Into the Spider-Verse",
  "Crazy Rich Asians", "The Favourite",
  "Eighth Grade", "Burning",
  "Shoplifters", "Capernaum",
  "Once Upon a Time in Hollywood",
  "Parasite", "Joker", "1917",
  "Knives Out", "Uncut Gems",
  "Ford v Ferrari", "The Irishman",
  "Marriage Story", "Little Women",
  "Jojo Rabbit", "Avengers: Endgame",
  "Toy Story 4", "Hustlers",
  "Booksmart", "Midsommar",

  // 2020s Essential (gaps)
  "Tenet", "Soul", "Nomadland",
  "Minari", "Promising Young Woman",
  "Sound of Metal", "Judas and the Black Messiah",
  "The Father", "Another Round",
  "The Trial of the Chicago 7", "Mank",
  "Palm Springs", "Borat Subsequent Moviefilm",
  "Spider-Man: No Way Home", "Dune",
  "No Time to Die", "The Power of the Dog",
  "CODA", "Don't Look Up",
  "West Side Story", "Belfast",
  "Drive My Car", "Licorice Pizza",
  "The French Dispatch", "Nightmare Alley",
  "The Tragedy of Macbeth",
  "Everything Everywhere All at Once", "Top Gun: Maverick",
  "Elvis", "The Banshees of Inisherin",
  "Tár", "The Fabelmans",
  "All Quiet on the Western Front (2022)",
  "Glass Onion", "The Menu",
  "Triangle of Sadness", "Women Talking",
  "Aftersun", "The Whale",
  "Babylon", "Nope", "Barbarian",
  "Smile", "Black Panther: Wakanda Forever",
  "Puss in Boots: The Last Wish", "M3GAN",
  "Oppenheimer", "Barbie", "Killers of the Flower Moon",
  "Poor Things", "The Holdovers",
  "Past Lives", "The Zone of Interest",
  "Anatomy of a Fall", "American Fiction",
  "Saltburn", "Maestro",
  "May December", "The Iron Claw",
  "Priscilla", "Dream Scenario",
  "The Boy and the Heron",
  "Godzilla Minus One",
  "Dune: Part Two", "Inside Out 2",
  "Deadpool & Wolverine", "Furiosa: A Mad Max Saga",
  "Alien: Romulus", "The Substance",
  "Conclave", "The Brutalist", "Anora",
  "Emilia Pérez", "Wicked", "Gladiator II",
  "Moana 2", "A Complete Unknown",
  "Nosferatu", "Nickel Boys",
  "I'm Still Here", "Challengers",
  "Civil War", "Twisters", "The Fall Guy",
  "The Wild Robot", "A Real Pain",
  "Sing Sing", "Hit Man",
  "Love Lies Bleeding", "Rebel Ridge",
  "Monkey Man", "Flow", "Robot Dreams",
  "Saturday Night", "Beetlejuice Beetlejuice",
];


/** All movies across all batches, deduplicated at runtime */
export const ALL_SEED_MOVIES: string[] = [
  ...BATCH_1, ...BATCH_2, ...BATCH_3, ...BATCH_4, ...BATCH_5, ...SUPPLEMENTAL,
];

/** Deduplicate a movie list (case-insensitive) */
export function deduplicateMovies(movies: string[]): string[] {
  const seen = new Set<string>();
  return movies.filter((m) => {
    const key = m.toLowerCase().trim();
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

/** Get a specific batch by number (1-6), or all if batch=0 */
export function getBatch(batch: number): string[] {
  switch (batch) {
    case 1: return BATCH_1;
    case 2: return BATCH_2;
    case 3: return BATCH_3;
    case 4: return BATCH_4;
    case 5: return BATCH_5;
    case 6: return SUPPLEMENTAL;
    default: return deduplicateMovies(ALL_SEED_MOVIES);
  }
}
